In [1]:
def empname(name):
    return name


In [2]:
empname("victor")

'victor'

In [3]:
def addnums(num1,num2):
    sum = num1+num2
    return sum

In [4]:
addnums(200,300)

500

In [5]:
addnums(200,"hello")

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [6]:
def myfunc(x):
    if(x == "MrRight"):
        print("welcome")
    else:
        print("you are not authorized")

In [7]:
myfunc("john")

you are not authorized


In [8]:
first = "queen"
last = "elizabeth"

In [9]:
first

'queen'

In [10]:
last

'elizabeth'

In [11]:
msg = first + ' [' + last + '] is a queen' 

In [12]:
msg

'queen [elizabeth] is a queen'

In [13]:
msgf = f'{first} {last} is a queen'

In [14]:
msgf

'queen elizabeth is a queen'

In [15]:
def greet_user():
    print("hi there!")
    print("welcome aboard!")


In [16]:
print("start")


start


In [17]:
greet_user()

hi there!
welcome aboard!


In [18]:
def greet_user2(name):
    print(f'Hi {name}!')
    print('Welcome aboard')

In [19]:
greet_user2("peter")

Hi peter!
Welcome aboard


In [20]:
def greet_user3(fname,lname):
    print(f'Hi {fname} {lname}!')
    print('Welcome aboard')

In [21]:
greet_user3("patrick","sean")

Hi patrick sean!
Welcome aboard


In [22]:
greet_user3(lname="john",fname="smith")

Hi smith john!
Welcome aboard


In [24]:
greet_user3("smith",lname="johny")

Hi smith johny!
Welcome aboard


In [25]:
greet_user3("smith",fname="johny")

TypeError: greet_user3() got multiple values for argument 'fname'

In [26]:
greet_user3(lname="johny","smith")

SyntaxError: positional argument follows keyword argument (<ipython-input-26-0946c9d97dfc>, line 1)

In [27]:
nums = [23,34,45,56,67,78]

In [28]:
type(nums)

list

In [31]:
def mult(num):
    return num * 10

In [32]:
mult(2)

20

In [34]:
for i in nums:
    x = mult(i)
    print(x)

230
340
450
560
670
780


In [35]:
nums

[23, 34, 45, 56, 67, 78]

In [36]:
y = map(lambda u: u * 10,nums)

In [37]:
y

In [38]:
for i in y:
    print(i)

230
340
450
560
670
780


In [39]:
friends = ['mary','peter','aj','patrick','susie']

In [40]:
FRIENDS = map(lambda o : o.upper(),friends)

In [42]:
for i in FRIENDS:
    print(i)

MARY
PETER
AJ
PATRICK
SUSIE


In [43]:
nums

[23, 34, 45, 56, 67, 78]

In [54]:
usingfilter = list(filter(lambda n: n%2==0,nums))

In [55]:
for i in usingfilter:
    print(i)

34
56
78


In [56]:
nums

[23, 34, 45, 56, 67, 78]

In [59]:
from functools import reduce
usingreduce = reduce((lambda x,y: x+y),nums)

In [60]:
print(usingreduce)

303


In [61]:
friends

['mary', 'peter', 'aj', 'patrick', 'susie']

In [62]:
for i in friends:
    print(i,friends.index(i))

mary 0
peter 1
aj 2
patrick 3
susie 4


In [63]:
#using enumerate func
for iposition,name in enumerate(friends):
    print(iposition,name)

0 mary
1 peter
2 aj
3 patrick
4 susie


In [65]:
store_a_map = dict((name,position) for position,name in enumerate(friends))

In [66]:
type(store_a_map)

dict

In [67]:
store_a_map

{'mary': 0, 'peter': 1, 'aj': 2, 'patrick': 3, 'susie': 4}

In [69]:
store_a_map.keys()


dict_keys(['mary', 'peter', 'aj', 'patrick', 'susie'])

In [70]:
store_a_map.values()

dict_values([0, 1, 2, 3, 4])

In [71]:
marks_list = range(10)

In [72]:
marks_list

range(0, 10)

In [74]:
for i in marks_list:
    print(i,end=",")

0,1,2,3,4,5,6,7,8,9,

In [75]:
semmarks_list = range(1,100
                    )

In [76]:
for i in semmarks_list:
    print(i,end=":")

1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20:21:22:23:24:25:26:27:28:29:30:31:32:33:34:35:36:37:38:39:40:41:42:43:44:45:46:47:48:49:50:51:52:53:54:55:56:57:58:59:60:61:62:63:64:65:66:67:68:69:70:71:72:73:74:75:76:77:78:79:80:81:82:83:84:85:86:87:88:89:90:91:92:93:94:95:96:97:98:99:

In [77]:
type(marks_list)

range

In [78]:
type(semmarks_list)

range

In [79]:
list_of_marks = list(reversed(marks_list))

In [80]:
list_of_marks

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [81]:
marks_list

range(0, 10)

In [82]:
markslist = list(marks_list)


In [83]:
markslist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
list_of_marks

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [85]:
zippedresult = zip(markslist,list_of_marks)

In [89]:
for i in zippedresult:
    print(i)

(0, 9)
(1, 8)
(2, 7)
(3, 6)
(4, 5)
(5, 4)
(6, 3)
(7, 2)
(8, 1)
(9, 0)


In [90]:
type(zippedresult)

zip

In [91]:
x = 100

In [97]:
y = int(input("enter a number: "))
if y > x :
    print("you entered a number not acceptable")
elif y==x:
    print("cool, you got number as wanted")
else:
    print("cool, you are still within limits")

enter a number:  100


cool, you got number as wanted


In [98]:
friends

['mary', 'peter', 'aj', 'patrick', 'susie']

In [99]:
bestfriends = []
for i in friends:
    if i!='aj':
        bestfriends.append(i)
        

In [100]:
bestfriends

['mary', 'peter', 'patrick', 'susie']

In [101]:
len(friends)

5

In [102]:
for i in range(0,len(friends)):
    print(i)

0
1
2
3
4


In [105]:
try:
    age = int(input('Age:'))
    income = 20000
    risk = income/age
    print(risk)
except ZeroDivisionError:
    print('Age cannot be 0')
except ValueError:
    print('Invalid value')

Age: hello


Invalid value


In [106]:
distance = [10,15,17,24]

In [107]:
time = [.30,.47,.55,1.20]

In [109]:
import numpy as np

In [114]:
np1 = np.array(distance)

In [113]:
np2 = np.array(time)

In [115]:
type(np1)

numpy.ndarray

In [116]:
speed = np1/np2

In [118]:
speed

array([33.33333333, 31.91489362, 30.90909091, 20.        ])

In [119]:
for i in speed:
    print(i)

33.333333333333336
31.914893617021278
30.909090909090907
20.0


In [120]:
first_numpy_array = np.array([1,3,5,7])

In [121]:
first_numpy_array

array([1, 3, 5, 7])

In [122]:
array_with_zeroes = np.zeros((3,3))

In [123]:
array_with_zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
array_with_ones = np.ones((3,3))

In [125]:
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [126]:
array_with_empty = np.empty((2,3))

In [127]:
array_with_empty

array([[4.67528219e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [128]:
np_arange = np.arange(12)

In [129]:
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [135]:
listx = [23,34,45]

In [136]:
arrtest = np.array(listx)

In [137]:
type(arrtest)

numpy.ndarray

In [138]:
arrtest

array([23, 34, 45])

In [139]:
listy = [100,200,300]

In [141]:
arrtest2 = np.array([listx,listy])

In [142]:
arrtest2

array([[ 23,  34,  45],
       [100, 200, 300]])

In [143]:
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [144]:
np_arange.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [145]:
np_arange.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [146]:
np_arange.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [147]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
#one dimensional array
oneD_array = np.arange(15)

In [149]:
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [150]:
oneD_array.ndim

1

In [151]:
oneD_array.shape

(15,)

In [152]:
oneD_array.size

15

In [153]:
twoD_array = oneD_array.reshape(3,5)

In [154]:
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [155]:
type(twoD_array)

numpy.ndarray

In [156]:
twoD_array.dtype

dtype('int64')

In [165]:
oneDnew_array = np.arange(27)


In [163]:
oneDnew_array

array(27)

In [166]:
threeD_array = oneDnew_array.reshape(3,3,3)

In [167]:
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [171]:
print(threeD_array.ndim,
threeD_array.shape,
threeD_array.size,
threeD_array.dtype)

3 (3, 3, 3) 27 int64


In [172]:
first_trial_cyclist = [10,15,17,24]

In [173]:
second_trial_cyclist = [12,11,21,24]

In [174]:
np_first_trial_cyclist = np.array(first_trial_cyclist)

In [175]:
np_second_trial_cylist = np.array(second_trial_cyclist)

In [176]:
result = np_first_trial_cyclist+np_second_trial_cylist

In [177]:
result

array([22, 26, 38, 48])

In [178]:
np.add(45,20)

65

In [179]:
np_daily_wage = np.array([7,8,9,11,13])*45

In [180]:
np_daily_wage

array([315, 360, 405, 495, 585])

In [181]:
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [182]:
oneD_array[0:3]

array([0, 1, 2])

In [189]:
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [190]:
twoD_array[0:2,0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [195]:
twoD_array[0][3]

3

In [193]:
twoD_array[2][0]

10

In [196]:
modtwoD_array = twoD_array[:,0:2]

In [197]:
modtwoD_array

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [2]:
import numpy as np
x = [23,34,23,43]

In [3]:
day1 = x * 6

In [4]:
len(day1)

24

In [5]:
day2 = x * 6

In [6]:
len(day2)

24

In [7]:
print(day1, end=" ")

[23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43] 

In [8]:
print(day2, end = " ")

[23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43] 

In [9]:
day1info = np.array(day1)

In [10]:
day1info

array([23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23,
       34, 23, 43, 23, 34, 23, 43])

In [11]:
day1info[day1info > 33]

array([34, 43, 34, 43, 34, 43, 34, 43, 34, 43, 34, 43])

In [12]:
day1infoup = day1info > 33

In [13]:
day1infoup

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [14]:
day1info[day1infoup]

array([34, 43, 34, 43, 34, 43, 34, 43, 34, 43, 34, 43])

In [15]:
friends = np.array(['mary', 'peter', 'aj', 'patrick', 'susie'])

In [16]:
friends

array(['mary', 'peter', 'aj', 'patrick', 'susie'], dtype='<U7')

In [17]:
friends.dtype

dtype('<U7')

In [18]:
friends.ndim

1

In [19]:
friends.shape

(5,)

In [20]:
friends_new = friends

In [21]:
friends

array(['mary', 'peter', 'aj', 'patrick', 'susie'], dtype='<U7')

In [22]:
friends_new

array(['mary', 'peter', 'aj', 'patrick', 'susie'], dtype='<U7')

In [23]:
friends_new is friends

True

In [24]:
nums = [23,34,45,56,67,78,89,90]

In [25]:
numsnp = np.array([nums])

In [26]:
numsnp

array([[23, 34, 45, 56, 67, 78, 89, 90]])

In [27]:
numsnp.dtype

dtype('int64')

In [28]:
numsnp2 = numsnp

In [29]:
numsnp2

array([[23, 34, 45, 56, 67, 78, 89, 90]])

In [30]:
numsnp is numsnp2

True

In [31]:
numsnp * 10

array([[230, 340, 450, 560, 670, 780, 890, 900]])

In [32]:
numsnp2

array([[23, 34, 45, 56, 67, 78, 89, 90]])

In [33]:
numsnp is numsnp2

True

In [34]:
numsnp

array([[23, 34, 45, 56, 67, 78, 89, 90]])

In [35]:
numsnp = np.array([23,34,45,56,67,78])

In [36]:
numsnp

array([23, 34, 45, 56, 67, 78])

In [37]:
numsnp2 = numsnp

In [39]:
numsnp2

array([23, 34, 45, 56, 67, 78])

In [40]:
numsnp2 is numsnp

True

In [47]:
numsnp = "hello"

In [49]:
numsnp

'hello'

In [67]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [51]:
numsnp2 is numsnp

False

In [68]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [69]:
numsnp3_vw = numsnp2.view()

In [70]:
numsnp2 is numsnp3_vw

False

In [71]:
len(numsnp2)

6

In [72]:
len(numsnp3_vw   )

6

In [73]:
numsnp3_vw[0] = 100

In [74]:
numsnp3_vw

array([100,  34,  45,  56,  67,  78])

In [75]:
numsnp2

array([100,  34,  45,  56,  67,  78])

In [76]:
numsnp2

array([100,  34,  45,  56,  67,  78])

In [77]:
numsnp2[0] = 1000

In [78]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [79]:
numsnp3_vw

array([1000,   34,   45,   56,   67,   78])

In [80]:
numsnp2 is numsnp3_vw

False

In [81]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [82]:
numsnp3_vw

array([1000,   34,   45,   56,   67,   78])

In [83]:
numsnp4 = numsnp2.copy()

In [84]:
numsnp4 is numsnp2

False

In [85]:
numsnp4

array([1000,   34,   45,   56,   67,   78])

In [86]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [87]:
numsnp4.reshape(2,3)

array([[1000,   34,   45],
       [  56,   67,   78]])

In [88]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [89]:
numsnp2[1]= 10000

In [90]:
numsnp2

array([ 1000, 10000,    45,    56,    67,    78])

In [91]:
numsnp4

array([1000,   34,   45,   56,   67,   78])

In [92]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,13,14,24,14,23]])

In [93]:
new_cyclist_trials


array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [94]:
new_cyclist_trials.ndim

2

In [95]:
new_cyclist_trials.shape

(2, 6)

In [96]:
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 13],
       [14, 24, 14, 23]])

In [97]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [98]:
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [99]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [100]:
new_cyclist_trials = new_cyclist_trials.ravel()

In [101]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [103]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [104]:
new_cyclist_trials.argmax()

3

In [105]:
new_cyclist_trials.argmin()

0

In [106]:
new_cyclist_trials.ndim

1

In [107]:
new_cyclist_trials = new_cyclist_trials.reshape(3,4)

In [109]:
new_cyclist_trials

array([[10, 15, 17, 26],
       [13, 19, 12, 13],
       [14, 24, 14, 23]])

In [110]:
np.hsplit(new_cyclist_trials,2)

[array([[10, 15],
        [13, 19],
        [14, 24]]),
 array([[17, 26],
        [12, 13],
        [14, 23]])]

In [112]:
new_cyclist_trials

array([[10, 15, 17, 26],
       [13, 19, 12, 13],
       [14, 24, 14, 23]])

In [113]:
new_cyclist_trials = new_cyclist_trials.ravel()

In [114]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [115]:
new_cyclist_trials1 = new_cyclist_trials.ravel()

In [116]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [117]:
new_cyclist_trials1

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [118]:
new_cyclist_trials = new_cyclist_trials1

In [120]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [121]:
new_cyclist_trials1

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [122]:
new_cyclist_trials is new_cyclist_trials1

True

In [123]:
x = new_cyclist_trials

In [124]:
x

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [125]:
y = new_cyclist_trials

In [126]:
y

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [127]:
x is y

True

In [128]:
new_cyclist_trials1 = np.array([[10,15,17,26,13,19],[12,13,14,24,14,23]])

In [129]:
new_cyclist_trials1

array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [130]:
new_cyclist_trials1 = new_cyclist_trials1.ravel()

In [131]:
new_cyclist_trials1

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [132]:
new_cyclist_trials2 = np.array([[10,15,17,26,13,19],[12,13,14,24,14,23]])

In [133]:
new_cyclist_trials2 = new_cyclist_trials2.ravel()

In [134]:
new_cyclist_trials2

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [138]:
stked = np.hstack((new_cyclist_trials1,new_cyclist_trials2))

In [139]:
stked

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23, 10, 15, 17, 26, 13,
       19, 12, 13, 14, 24, 14, 23])

In [140]:
stked

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23, 10, 15, 17, 26, 13,
       19, 12, 13, 14, 24, 14, 23])

In [152]:
test = list(map((lambda n: n* 100),stked))


In [153]:
test2 = sorted(test)

In [156]:
print(test2,end=",")

[1000, 1000, 1200, 1200, 1300, 1300, 1300, 1300, 1400, 1400, 1400, 1400, 1500, 1500, 1700, 1700, 1900, 1900, 2300, 2300, 2400, 2400, 2600, 2600],

In [157]:
stked

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23, 10, 15, 17, 26, 13,
       19, 12, 13, 14, 24, 14, 23])

In [159]:
stked * 100

array([1000, 1500, 1700, 2600, 1300, 1900, 1200, 1300, 1400, 2400, 1400,
       2300, 1000, 1500, 1700, 2600, 1300, 1900, 1200, 1300, 1400, 2400,
       1400, 2300])

In [160]:
test_data = np.array([[23,34,45,56],[34,45,56,67]])

In [161]:
test_data

array([[23, 34, 45, 56],
       [34, 45, 56, 67]])

In [162]:
test_data.transpose()

array([[23, 34],
       [34, 45],
       [45, 56],
       [56, 67]])

In [163]:
test_data

array([[23, 34, 45, 56],
       [34, 45, 56, 67]])

In [164]:
test_data = test_data.transpose()

In [165]:
test_data

array([[23, 34],
       [34, 45],
       [45, 56],
       [56, 67]])

In [166]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])

In [167]:
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [168]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [169]:
np.linalg.matrix_rank(A)

3

In [170]:
np.trace(A)

11

In [171]:
np.linalg.det(A)

-306.0

In [172]:
countries = np.array(['luxembourg','Norway','Japan','Switzerland','USA','Qatar'])

In [173]:
gdp_per_capita = np.array([52056.1234,40345.4565,45456.78564,33245.56782,34544.45888])

In [174]:
max_gdp_per_capita = gdp_per_capita.argmax()

In [175]:
max_gdp_per_capita

0

In [178]:
country_with_max_gdp_per_capita = countries[max_gdp_per_capita]

In [179]:
country_with_max_gdp_per_capita

'luxembourg'

In [180]:
for country in countries:
    print('ecalculating country {}'.format(country))

ecalculating country luxembourg
ecalculating country Norway
ecalculating country Japan
ecalculating country Switzerland
ecalculating country USA
ecalculating country Qatar


In [181]:
for i in range(len(countries)-1):
    country = countries[i]
    country_gdp_per_capita = gdp_per_capita[i]
    print('country {} per capita gdp is {}'.format(country,country_gdp_per_capita))

country luxembourg per capita gdp is 52056.1234
country Norway per capita gdp is 40345.4565
country Japan per capita gdp is 45456.78564
country Switzerland per capita gdp is 33245.56782
country USA per capita gdp is 34544.45888


In [182]:
import pandas as pd

In [183]:
ser1 = pd.Series('welcome')

In [184]:
type(ser1)

pandas.core.series.Series

In [185]:
ser1

0    welcome
dtype: object

In [189]:
ser1 = pd.Series(['welcome','hello','cool'])

In [190]:
ser1

0    welcome
1      hello
2       cool
dtype: object

In [191]:
ser2 = pd.Series(list('abcdefgh'))

In [192]:
ser2

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
dtype: object

In [193]:
countries

array(['luxembourg', 'Norway', 'Japan', 'Switzerland', 'USA', 'Qatar'],
      dtype='<U11')

In [194]:
cdata = pd.Series(countries)

In [195]:
cdata

0     luxembourg
1         Norway
2          Japan
3    Switzerland
4            USA
5          Qatar
dtype: object

In [196]:
countries

array(['luxembourg', 'Norway', 'Japan', 'Switzerland', 'USA', 'Qatar'],
      dtype='<U11')

In [197]:
gdp_per_capita

array([52056.1234 , 40345.4565 , 45456.78564, 33245.56782, 34544.45888])

In [200]:
gdp_per_capita = np.array([52056.1234 , 40345.4565 , 45456.78564, 33245.56782, 34544.45888,34544.45845])

In [201]:
gdpdata = pd.Series(gdp_per_capita,index=countries)

In [202]:
gdpdata

luxembourg     52056.12340
Norway         40345.45650
Japan          45456.78564
Switzerland    33245.56782
USA            34544.45888
Qatar          34544.45845
dtype: float64

In [203]:
gdpdata2 = pd.Series(gdp_per_capita)

In [204]:
gdpdata2

0    52056.12340
1    40345.45650
2    45456.78564
3    33245.56782
4    34544.45888
5    34544.45845
dtype: float64

In [205]:
scalar_series = pd.Series(5,index=['a','b','c'])

In [206]:
scalar_series

a    5
b    5
c    5
dtype: int64

In [207]:
gdpdata[0]

52056.1234

In [208]:
gdpdata[-5]

40345.4565

In [209]:
gdpdata['USA']

34544.45888

In [210]:
gdpdata.loc['USA']

34544.45888

In [212]:
gdpdata.iloc[0]

52056.1234

In [213]:
ser = pd.Series([4, 7, -5, 3])

In [214]:
ser

0    4
1    7
2   -5
3    3
dtype: int64

In [215]:
ser.values

array([ 4,  7, -5,  3])

In [216]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [217]:
ser

0    4
1    7
2   -5
3    3
dtype: int64

In [218]:
ser2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [219]:
ser2

d    4
b    7
a   -5
c    3
dtype: int64

In [220]:
ser2['b']

7

In [221]:
ser2['b'] = 17

In [222]:
ser2

d     4
b    17
a    -5
c     3
dtype: int64

In [226]:
ser2[['c','d']]

c    3
d    4
dtype: int64

In [227]:
ser2[ser2 > 0]

d     4
b    17
c     3
dtype: int64

In [228]:
ser2

d     4
b    17
a    -5
c     3
dtype: int64

In [229]:
np.exp(ser2)

d    5.459815e+01
b    2.415495e+07
a    6.737947e-03
c    2.008554e+01
dtype: float64

In [230]:
'b' in ser2

True

In [231]:
sdata = {'paris': 35000, 'germany': 71000, 'greece': 16000, 'norway': 5000}

In [233]:
type(sdata)

dict

In [240]:
sdata.keys()

dict_keys(['paris', 'germany', 'greece', 'norway'])

In [241]:
sdata.values()

dict_values([35000, 71000, 16000, 5000])

In [242]:
ser3 = pd.Series(sdata)

In [243]:
ser3

paris      35000
germany    71000
greece     16000
norway      5000
dtype: int64

In [244]:
country = ['greece', 'paris', 'germany', 'norway']

In [245]:
ser4 = pd.Series(sdata, index=country)

In [246]:
ser4

greece     16000
paris      35000
germany    71000
norway      5000
dtype: int64

In [247]:
pd.isnull(ser4)

greece     False
paris      False
germany    False
norway     False
dtype: bool

In [248]:
result = ser3 + ser4

In [249]:
result

germany    142000
greece      32000
norway      10000
paris       70000
dtype: int64

In [252]:
ser4.name = 'population'

In [253]:
ser4

greece     16000
paris      35000
germany    71000
norway      5000
Name: population, dtype: int64

In [254]:
ser4.index.name = 'country'

In [255]:
ser4

country
greece     16000
paris      35000
germany    71000
norway      5000
Name: population, dtype: int64

In [13]:
data = {'eucountry': ['paris', 'germany', 'austria', 'sweden', 'Norway'],
'year': [2000, 2001, 2002, 2001, 2002],
'popul': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [2]:
type(data)

dict

In [3]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(data)

In [4]:
frame

eucountry  year  popul
0     paris  2000    1.5
1   germany  2001    1.7
2   austria  2002    3.6
3    sweden  2001    2.4
4    Norway  2002    2.9

In [7]:
frame2 = pd.DataFrame(data, columns=['year','eucountry','popul'])

In [8]:
frame2

year eucountry  popul
0  2000     paris    1.5
1  2001   germany    1.7
2  2002   austria    3.6
3  2001    sweden    2.4
4  2002    Norway    2.9

In [14]:
frame3 = pd.DataFrame(data, columns=['year', 'eucountry', 'popul', 'debt'],
	 index=['one', 'two', 'three', 'four', 'five'])

In [10]:
frame3

year eucountry  popul debt
one    2000     paris    1.5  NaN
two    2001   germany    1.7  NaN
three  2002   austria    3.6  NaN
four   2001    sweden    2.4  NaN
five   2002    Norway    2.9  NaN

In [11]:
print(frame3['eucountry'])

one        paris
two      germany
three    austria
four      sweden
five      Norway
Name: eucountry, dtype: object


In [12]:
frame3.loc['three']

year            2002
eucountry    austria
popul            3.6
debt             NaN
Name: three, dtype: object

In [13]:
frame3.iloc[3]

year           2001
eucountry    sweden
popul           2.4
debt            NaN
Name: four, dtype: object

In [14]:
frame3

year eucountry  popul debt
one    2000     paris    1.5  NaN
two    2001   germany    1.7  NaN
three  2002   austria    3.6  NaN
four   2001    sweden    2.4  NaN
five   2002    Norway    2.9  NaN

In [15]:
frame3['debt'] = 16.5

In [16]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5  16.5
two    2001   germany    1.7  16.5
three  2002   austria    3.6  16.5
four   2001    sweden    2.4  16.5
five   2002    Norway    2.9  16.5

In [17]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5  16.5
two    2001   germany    1.7  16.5
three  2002   austria    3.6  16.5
four   2001    sweden    2.4  16.5
five   2002    Norway    2.9  16.5

In [18]:
frame3['debt'] = np.arange(5.)

In [19]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5   0.0
two    2001   germany    1.7   1.0
three  2002   austria    3.6   2.0
four   2001    sweden    2.4   3.0
five   2002    Norway    2.9   4.0

In [20]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [21]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [22]:
frame3['debt'] = val

In [24]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5   NaN
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [25]:
frame3['eastern'] = frame3.eucountry == 'paris'

In [26]:
frame3

year eucountry  popul  debt  eastern
one    2000     paris    1.5   NaN     True
two    2001   germany    1.7  -1.2    False
three  2002   austria    3.6   NaN    False
four   2001    sweden    2.4  -1.5    False
five   2002    Norway    2.9  -1.7    False

In [27]:
del frame3['eastern']

In [28]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5   NaN
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [29]:
frame3.drop(['one'])

year eucountry  popul  debt
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [30]:
frame3.drop(frame3.index[0])

year eucountry  popul  debt
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [31]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5   NaN
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [3]:
pop = {'norway': {2001: 2.4, 2002: 2.9},
	'denmark': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [4]:
pop

{'norway': {2001: 2.4, 2002: 2.9},
 'denmark': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [6]:
import pandas as pd
import numpy as np
frame4 = pd.DataFrame(pop)

In [7]:
frame4

norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2000     NaN      1.5

In [8]:
frame4.T

2001  2002  2000
norway    2.4   2.9   NaN
denmark   1.7   3.6   1.5

In [9]:
frame4

norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2000     NaN      1.5

In [10]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2003     NaN      NaN

In [17]:
frame3

year eucountry  popul debt
one    2000     paris    1.5  NaN
two    2001   germany    1.7  NaN
three  2002   austria    3.6  NaN
four   2001    sweden    2.4  NaN
five   2002    Norway    2.9  NaN

In [19]:
pop = {'norway': {2001: 2.4, 2002: 2.9},
	'denmark': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [20]:
pop

{'norway': {2001: 2.4, 2002: 2.9},
 'denmark': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [21]:
frame3 = pd.DataFrame(pop)

In [22]:
frame3

norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2000     NaN      1.5

In [23]:
pdata = {'norway': frame3['norway'][:-1],
	'denmark': frame3['denmark'][:2]}

In [24]:
pdata

{'norway': 2001    2.4
 2002    2.9
 Name: norway, dtype: float64,
 'denmark': 2001    1.7
 2002    3.6
 Name: denmark, dtype: float64}

In [25]:
frame3

norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2000     NaN      1.5

In [26]:
frame3.index.name = 'year'; 

In [27]:
frame3.columns.name = 'eucountry'

In [28]:
frame3

eucountry  norway  denmark
year                      
2001          2.4      1.7
2002          2.9      3.6
2000          NaN      1.5

In [30]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [31]:
item = pd.Series(range(3),index = ['a','b','c'])

In [32]:
item

a    0
b    1
c    2
dtype: int64

In [33]:
index = item.index

In [34]:
index

Index(['a', 'b', 'c'], dtype='object')

In [35]:
index[1:]

Index(['b', 'c'], dtype='object')

In [36]:
index

Index(['a', 'b', 'c'], dtype='object')

In [37]:
index[0] = 'm'

TypeError: Index does not support mutable operations

In [38]:
index = pd.Index(np.arange(3))

In [39]:
index

Int64Index([0, 1, 2], dtype='int64')

In [40]:
item2 = pd.Series([1,2,3],index=index)

In [41]:
item2

0    1
1    2
2    3
dtype: int64

In [42]:
item2.index is index

True

In [43]:
pop = {'norway': {2001: 2.4, 2002: 2.9},
	'denmark': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [44]:
frame3 = pd.DataFrame(pop)

In [45]:
frame3

norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2000     NaN      1.5

In [46]:
'norway' in frame3.columns

True

In [47]:
2003 in frame3.index

False

In [48]:
ser = pd.Series([1,2,3,4], index=['d','b','c','a'])

In [49]:
ser

d    1
b    2
c    3
a    4
dtype: int64

In [50]:
ser1 = ser.reindex(['a','b','c','d'])

In [51]:
ser1

a    4
b    2
c    3
d    1
dtype: int64

In [52]:
ser3 = ser1.reindex(['a','b','c','d','e'])

In [53]:
ser3

a    4.0
b    2.0
c    3.0
d    1.0
e    NaN
dtype: float64

In [54]:
ser3 = ser1.reindex(['a','b','c','d','e'],fill_value=0)

In [55]:
ser3

a    4
b    2
c    3
d    1
e    0
dtype: int64

In [56]:
ser4 = pd.Series(['cricket','football','basketball'],index=[0,2,4])

In [57]:
ser4

0       cricket
2      football
4    basketball
dtype: object

In [61]:
ser4.reindex(range(6),method='ffill')

0       cricket
1       cricket
2      football
3      football
4    basketball
5    basketball
dtype: object

In [62]:
ser5 = pd.Series(['cricket','football','basketball'],index=[0,2,4])

In [63]:
ser5.reindex(range(6),method='bfill')

0       cricket
1      football
2      football
3    basketball
4    basketball
5           NaN
dtype: object

In [64]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),index=['a','b','c'],
columns=['ger','aus','fra'])

In [65]:
frame

ger  aus  fra
a    0    1    2
b    3    4    5
c    6    7    8

In [66]:
frame2 = frame.reindex(['a','b','c','d'])

In [67]:
frame2

ger  aus  fra
a  0.0  1.0  2.0
b  3.0  4.0  5.0
c  6.0  7.0  8.0
d  NaN  NaN  NaN

In [68]:
country = ['ger','norway','fra']

In [69]:
frame.reindex(columns = country)

ger  norway  fra
a    0     NaN    2
b    3     NaN    5
c    6     NaN    8

In [70]:
frame

ger  aus  fra
a    0    1    2
b    3    4    5
c    6    7    8

In [72]:
ser6 = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [73]:
ser6

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [74]:
new_ser = ser6.drop('c')

In [76]:
new_ser

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [77]:
ser6.drop(['a','c'])

b    1.0
d    3.0
e    4.0
dtype: float64

In [78]:
ser6

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [79]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['paris', 'belgium', 'vienna', 'basel'],
columns=['one', 'two', 'three', 'four'])

In [80]:
data

one  two  three  four
paris      0    1      2     3
belgium    4    5      6     7
vienna     8    9     10    11
basel     12   13     14    15

In [81]:
print(data.drop(['paris','belgium']))

        one  two  three  four
vienna    8    9     10    11
basel    12   13     14    15


In [82]:
data

one  two  three  four
paris      0    1      2     3
belgium    4    5      6     7
vienna     8    9     10    11
basel     12   13     14    15

In [89]:
data.drop('two',axis=1)

one  three  four
paris      0      2     3
belgium    4      6     7
vienna     8     10    11
basel     12     14    15

In [90]:
data

one  two  three  four
paris      0    1      2     3
belgium    4    5      6     7
vienna     8    9     10    11
basel     12   13     14    15

In [91]:
print(data.drop(['two', 'four'], axis=1))

         one  three
paris      0      2
belgium    4      6
vienna     8     10
basel     12     14


In [92]:
ser7 = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [93]:
ser7

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [94]:
ser7['a']

0.0

In [95]:
ser7[1]

1.0

In [96]:
ser7[1] == ser7['b']

True

In [97]:
ser7[2:4]

c    2.0
d    3.0
dtype: float64

In [98]:
ser7[[1,3]]

b    1.0
d    3.0
dtype: float64

In [99]:
ser7[ser7>2]

d    3.0
dtype: float64

In [100]:
ser7['b':'c']

b    1.0
c    2.0
dtype: float64

In [101]:
data1 = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['paris', 'belgium', 'vienna', 'basel'],
columns=['one', 'two', 'three', 'four'])

In [102]:
data1

one  two  three  four
paris      0    1      2     3
belgium    4    5      6     7
vienna     8    9     10    11
basel     12   13     14    15

In [103]:
data1['two']

paris       1
belgium     5
vienna      9
basel      13
Name: two, dtype: int64

In [104]:
data1[['three','one']]

three  one
paris        2    0
belgium      6    4
vienna      10    8
basel       14   12

In [105]:
data1[:2]

one  two  three  four
paris      0    1      2     3
belgium    4    5      6     7

In [106]:
data1[data1['three'] > 5]

one  two  three  four
belgium    4    5      6     7
vienna     8    9     10    11
basel     12   13     14    15

In [107]:
data1

one  two  three  four
paris      0    1      2     3
belgium    4    5      6     7
vienna     8    9     10    11
basel     12   13     14    15

In [111]:
data1.loc['belgium',['two','three']]

two      5
three    6
Name: belgium, dtype: int64

In [109]:
data1.loc[:'belgium','two']

paris      1
belgium    5
Name: two, dtype: int64

In [110]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [112]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [113]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [114]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [115]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [116]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
index=['Ohio', 'Texas', 'Colorado'])

In [117]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [118]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [119]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [120]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [121]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [122]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

In [123]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [124]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [125]:
newdf = df1.add(df2, fill_value=0)

In [126]:
newdf

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [127]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [128]:
newdf1 = df1.reindex(columns=df2.columns, fill_value=0)

In [129]:
newdf1

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [130]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [131]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [133]:
arr = np.arange(12.).reshape((3, 4))

In [134]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [135]:
print(arr[0])

[0. 1. 2. 3.]


In [136]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [137]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
index=['germany', 'austria', 'russia', 'sweden'])

In [138]:
frame

b     d     e
germany  0.0   1.0   2.0
austria  3.0   4.0   5.0
russia   6.0   7.0   8.0
sweden   9.0  10.0  11.0

In [139]:
series = frame.loc['germany']

In [140]:
series

b    0.0
d    1.0
e    2.0
Name: germany, dtype: float64

In [141]:
print(frame - series)

           b    d    e
germany  0.0  0.0  0.0
austria  3.0  3.0  3.0
russia   6.0  6.0  6.0
sweden   9.0  9.0  9.0


In [142]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [143]:
series2

b    0
e    1
f    2
dtype: int64

In [144]:
frame+series2

b   d     e   f
germany  0.0 NaN   3.0 NaN
austria  3.0 NaN   6.0 NaN
russia   6.0 NaN   9.0 NaN
sweden   9.0 NaN  12.0 NaN

In [145]:
series3 = frame['d']

In [146]:
series3

germany     1.0
austria     4.0
russia      7.0
sweden     10.0
Name: d, dtype: float64

In [147]:
frame.sub(series3, axis=0)

b    d    e
germany -1.0  0.0  1.0
austria -1.0  0.0  1.0
russia  -1.0  0.0  1.0
sweden  -1.0  0.0  1.0

In [148]:
frame

b     d     e
germany  0.0   1.0   2.0
austria  3.0   4.0   5.0
russia   6.0   7.0   8.0
sweden   9.0  10.0  11.0

In [149]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
index=['germany', 'austria', 'russia', 'sweden'])

In [150]:
frame

b         d         e
germany -0.221374 -0.893239 -0.571898
austria  0.561266  1.630709  1.262118
russia  -0.062532 -0.321379  1.864805
sweden  -3.594233  0.897001  0.111311

In [151]:
np.abs(frame)

b         d         e
germany  0.221374  0.893239  0.571898
austria  0.561266  1.630709  1.262118
russia   0.062532  0.321379  1.864805
sweden   3.594233  0.897001  0.111311

In [152]:
f = lambda x: x.max() - x.min()

In [153]:
f

<function __main__.<lambda>(x)>

In [154]:
frame.apply(f)

b    4.155498
d    2.523949
e    2.436703
dtype: float64

In [155]:
print(frame.apply(f, axis=1))

germany    0.671866
austria    1.069444
russia     2.186185
sweden     4.491234
dtype: float64


In [156]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [159]:
frame.apply(f)

b         d         e
min -3.594233 -0.893239 -0.571898
max  0.561266  1.630709  1.864805

In [160]:
format = lambda x: '%.2f' % x

In [161]:
frame.applymap(format)

b      d      e
germany  -0.22  -0.89  -0.57
austria   0.56   1.63   1.26
russia   -0.06  -0.32   1.86
sweden   -3.59   0.90   0.11

In [162]:
frame

b         d         e
germany -0.221374 -0.893239 -0.571898
austria  0.561266  1.630709  1.262118
russia  -0.062532 -0.321379  1.864805
sweden  -3.594233  0.897001  0.111311

In [163]:
print(frame['e'].map(format))

germany    -0.57
austria     1.26
russia      1.86
sweden      0.11
Name: e, dtype: object


In [165]:
ser8 = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [166]:
ser8

d    0
a    1
b    2
c    3
dtype: int64

In [167]:
ser8.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [171]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
columns=['d', 'a', 'b', 'c'])

In [172]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [173]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [174]:
frame.sort_index(axis=0)

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [175]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [176]:
print(frame.sort_index(axis=1, ascending=False))

       d  c  b  a
three  0  3  2  1
one    4  7  6  5


In [177]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [178]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [183]:
#to be checked
print(frame.sort_index(by='b'))

TypeError: sort_index() got an unexpected keyword argument 'by'

In [184]:
ser10 = pd.Series([7,-5,7,4,2,0,4])

In [185]:
ser10

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [186]:
ser10.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [187]:
ser10.rank(ascending = False)

0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64

In [188]:
print(ser10.rank(method='first'))

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64


In [189]:
ser11 = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [190]:
ser11

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [192]:
ser11.iloc[1]

1

In [193]:
ser11['a']

a    0
a    1
dtype: int64

In [194]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [195]:
df

0         1         2
a -0.914659  0.975178 -1.203979
a  0.958359 -0.640692 -1.622290
b -0.278075  0.997847 -0.140620
b  0.514605 -0.479675 -0.991544

In [196]:
df.loc['b']

0         1         2
b -0.278075  0.997847 -0.140620
b  0.514605 -0.479675 -0.991544

In [197]:
df.sum()

0    0.280229
1    0.852658
2   -3.958433
dtype: float64

In [198]:
df.sum(axis=1)

a   -1.143461
a   -1.304624
b    0.579152
b   -0.956614
dtype: float64

In [199]:
df.mean(axis=1, skipna=False)

a   -0.381154
a   -0.434875
b    0.193051
b   -0.318871
dtype: float64

In [200]:
df.describe


<bound method NDFrame.describe of           0         1         2
a -0.914659  0.975178 -1.203979
a  0.958359 -0.640692 -1.622290
b -0.278075  0.997847 -0.140620
b  0.514605 -0.479675 -0.991544>

In [201]:
ser12 = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [202]:
ser12.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [220]:
ser13 = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [221]:
uniques = ser13.unique()

In [222]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [223]:
uniques.sort()

In [224]:
uniques

array(['a', 'b', 'c', 'd'], dtype=object)

In [225]:
ser13.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [226]:
string_data = pd.Series(['apple', 'orange', np.nan, 'avocado','grapes'])

In [227]:
string_data

0      apple
1     orange
2        NaN
3    avocado
4     grapes
dtype: object

In [228]:
string_data.isnull()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [229]:
string_data[0] = None

In [230]:
string_data

0       None
1     orange
2        NaN
3    avocado
4     grapes
dtype: object

In [232]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])

In [233]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [234]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [235]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],
[NA, NA, NA], [NA, 6.5, 3.]])

In [236]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [237]:
cleaned_data = data.dropna()

In [238]:
cleaned_data

0    1    2
0  1.0  6.5  3.0

In [239]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [240]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [241]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [242]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [243]:
df = pd.DataFrame(np.random.randn(7, 3))

In [244]:
df

0         1         2
0 -0.106245  0.034892  0.787884
1  1.400250 -0.974597  0.384107
2 -0.734916 -1.053978 -0.711990
3 -0.849477 -1.693999 -0.402919
4 -0.474250 -0.577960  0.456840
5 -0.618078 -0.806184  0.166851
6 -0.411457 -0.766150  1.077469

In [245]:
df.loc[:4, 1] = NA

In [246]:
df

0         1         2
0 -0.106245       NaN  0.787884
1  1.400250       NaN  0.384107
2 -0.734916       NaN -0.711990
3 -0.849477       NaN -0.402919
4 -0.474250       NaN  0.456840
5 -0.618078 -0.806184  0.166851
6 -0.411457 -0.766150  1.077469

In [247]:
df.loc[:2, 2] = NA

In [248]:
df

0         1         2
0 -0.106245       NaN       NaN
1  1.400250       NaN       NaN
2 -0.734916       NaN       NaN
3 -0.849477       NaN -0.402919
4 -0.474250       NaN  0.456840
5 -0.618078 -0.806184  0.166851
6 -0.411457 -0.766150  1.077469

In [249]:
df1=df.dropna(thresh=3)

In [250]:
df1

0         1         2
5 -0.618078 -0.806184  0.166851
6 -0.411457 -0.766150  1.077469

In [251]:
df.fillna(0)

0         1         2
0 -0.106245  0.000000  0.000000
1  1.400250  0.000000  0.000000
2 -0.734916  0.000000  0.000000
3 -0.849477  0.000000 -0.402919
4 -0.474250  0.000000  0.456840
5 -0.618078 -0.806184  0.166851
6 -0.411457 -0.766150  1.077469

In [252]:
df

0         1         2
0 -0.106245       NaN       NaN
1  1.400250       NaN       NaN
2 -0.734916       NaN       NaN
3 -0.849477       NaN -0.402919
4 -0.474250       NaN  0.456840
5 -0.618078 -0.806184  0.166851
6 -0.411457 -0.766150  1.077469

In [254]:
df.fillna({1: 0.5, 2: -1})

0         1         2
0 -0.106245  0.500000 -1.000000
1  1.400250  0.500000 -1.000000
2 -0.734916  0.500000 -1.000000
3 -0.849477  0.500000 -0.402919
4 -0.474250  0.500000  0.456840
5 -0.618078 -0.806184  0.166851
6 -0.411457 -0.766150  1.077469

In [255]:
_

0         1         2
0 -0.106245  0.500000 -1.000000
1  1.400250  0.500000 -1.000000
2 -0.734916  0.500000 -1.000000
3 -0.849477  0.500000 -0.402919
4 -0.474250  0.500000  0.456840
5 -0.618078 -0.806184  0.166851
6 -0.411457 -0.766150  1.077469

In [256]:
_ = df.fillna(0, inplace=True)

In [257]:
df

0         1         2
0 -0.106245  0.000000  0.000000
1  1.400250  0.000000  0.000000
2 -0.734916  0.000000  0.000000
3 -0.849477  0.000000 -0.402919
4 -0.474250  0.000000  0.456840
5 -0.618078 -0.806184  0.166851
6 -0.411457 -0.766150  1.077469

In [258]:
df = pd.DataFrame(np.random.randn(6, 3))

In [259]:
df

0         1         2
0  0.375774 -1.324489 -0.006635
1 -0.786441  0.515692 -1.420352
2  1.636048  0.634210 -0.340613
3 -0.651393 -1.160713 -0.093021
4 -0.063065 -0.236809 -0.125541
5 -1.399987  1.380581 -0.450904

In [261]:
df.loc[2:, 1] = NA

In [262]:
df.loc[4:, 2] = NA

In [263]:
df

0         1         2
0  0.375774 -1.324489 -0.006635
1 -0.786441  0.515692 -1.420352
2  1.636048       NaN -0.340613
3 -0.651393       NaN -0.093021
4 -0.063065       NaN       NaN
5 -1.399987       NaN       NaN

In [264]:
df.fillna(method='ffill')

0         1         2
0  0.375774 -1.324489 -0.006635
1 -0.786441  0.515692 -1.420352
2  1.636048  0.515692 -0.340613
3 -0.651393  0.515692 -0.093021
4 -0.063065  0.515692 -0.093021
5 -1.399987  0.515692 -0.093021

In [265]:
df.fillna(method='ffill', limit=2)

0         1         2
0  0.375774 -1.324489 -0.006635
1 -0.786441  0.515692 -1.420352
2  1.636048  0.515692 -0.340613
3 -0.651393  0.515692 -0.093021
4 -0.063065       NaN -0.093021
5 -1.399987       NaN -0.093021

In [267]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [268]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [269]:
test = pd.DataFrame(data,columns = ['values'])

In [270]:
test

values
0     1.0
1     NaN
2     3.5
3     NaN
4     7.0

In [272]:
test['newval'] = test['values'] * 100

In [273]:
test

values  newval
0     1.0   100.0
1     NaN     NaN
2     3.5   350.0
3     NaN     NaN
4     7.0   700.0

In [274]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [275]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [276]:
data.describe()

count    3.000000
mean     3.833333
std      3.013857
min      1.000000
25%      2.250000
50%      3.500000
75%      5.250000
max      7.000000
dtype: float64

In [277]:
data = pd.Series(np.random.randn(10),
index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
[1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])

In [278]:
data

a  1   -0.566271
   2    0.164967
   3   -1.931699
b  1    0.565327
   2   -0.695005
   3   -1.942233
c  1   -1.197321
   2   -0.952478
d  2    0.344292
   3   -0.611913
dtype: float64

In [279]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [280]:
data['b']

1    0.565327
2   -0.695005
3   -1.942233
dtype: float64

In [281]:
data['b':'c']

b  1    0.565327
   2   -0.695005
   3   -1.942233
c  1   -1.197321
   2   -0.952478
dtype: float64

In [282]:
data.loc[['b', 'd']]

b  1    0.565327
   2   -0.695005
   3   -1.942233
d  2    0.344292
   3   -0.611913
dtype: float64

In [283]:
data[:, 2]

a    0.164967
b   -0.695005
c   -0.952478
d    0.344292
dtype: float64

In [284]:
data.unstack()

1         2         3
a -0.566271  0.164967 -1.931699
b  0.565327 -0.695005 -1.942233
c -1.197321 -0.952478       NaN
d       NaN  0.344292 -0.611913

In [285]:
data

a  1   -0.566271
   2    0.164967
   3   -1.931699
b  1    0.565327
   2   -0.695005
   3   -1.942233
c  1   -1.197321
   2   -0.952478
d  2    0.344292
   3   -0.611913
dtype: float64

In [286]:
data.unstack().stack()

a  1   -0.566271
   2    0.164967
   3   -1.931699
b  1    0.565327
   2   -0.695005
   3   -1.942233
c  1   -1.197321
   2   -0.952478
d  2    0.344292
   3   -0.611913
dtype: float64

In [287]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
columns=[['germany', 'france', 'sweden'],
['Green', 'Red', 'Green']])

In [288]:
frame

germany france sweden
      Green    Red  Green
a 1       0      1      2
  2       3      4      5
b 1       6      7      8
  2       9     10     11

In [289]:
frame.index.names = ['key1', 'key2']

In [290]:
frame

germany france sweden
            Green    Red  Green
key1 key2                      
a    1          0      1      2
     2          3      4      5
b    1          6      7      8
     2          9     10     11

In [291]:
frame.columns.names = ['state', 'color']

In [292]:
frame

state     germany france sweden
color       Green    Red  Green
key1 key2                      
a    1          0      1      2
     2          3      4      5
b    1          6      7      8
     2          9     10     11

In [293]:
frame['germany']

color      Green
key1 key2       
a    1         0
     2         3
b    1         6
     2         9

In [294]:
frame.swaplevel('key1', 'key2')

state     germany france sweden
color       Green    Red  Green
key2 key1                      
1    a          0      1      2
2    a          3      4      5
1    b          6      7      8
2    b          9     10     11

In [295]:
frame.sum(level='key2')

state germany france sweden
color   Green    Red  Green
key2                       
1           6      8     10
2          12     14     16

In [296]:
frame.sum(level='color', axis=1)

color      Green  Red
key1 key2            
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [297]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
'c': ['one', 'one', 'one', 'two', 'two', 'two', 'two'],
'd': [0, 1, 2, 0, 1, 2, 3]})

In [298]:
frame

a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [299]:
frame2 = frame.set_index(['c', 'd'])

In [300]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [301]:
frame3 = frame.set_index(['c', 'd'], drop=False)

In [302]:
frame3

a  b    c  d
c   d              
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [303]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [304]:
frame2.reset_index()

c  d  a  b
0  one  0  0  7
1  one  1  1  6
2  one  2  2  5
3  two  0  3  4
4  two  1  4  3
5  two  2  5  2
6  two  3  6  1

In [305]:
frame2

a  b
c   d      
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

In [306]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})

In [307]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [308]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [309]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [310]:
pd.merge(df1, df2, on='key')

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [311]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],'data2': range(3)})

In [312]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [313]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [314]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [315]:
pd.merge(df3, df4)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [316]:
pd.merge(df1, df2, how='outer')

key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [317]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})
df2 = pd.DataFrame({'key': ['a', 'b', 'a', 'b', 'd'],'data2': range(5)})

In [318]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [319]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [320]:
pd.merge(df1, df2, on='key', how='left')

key  data1  data2
0    b      0    1.0
1    b      0    3.0
2    b      1    1.0
3    b      1    3.0
4    a      2    0.0
5    a      2    2.0
6    c      3    NaN
7    a      4    0.0
8    a      4    2.0
9    b      5    1.0
10   b      5    3.0

In [321]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],'key2': ['one', 'two', 'one'],'lval': [1, 2, 3]})
print(left)

right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],'key2': ['one', 'one', 'one', 'two'],'rval': [4, 5, 6, 7]})
print(right)

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3
  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7


In [322]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [323]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [324]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [325]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [326]:
right1

group_val
a        3.5
b        7.0

In [327]:
pd.merge(left1, right1, left_on='key', right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [328]:
lefth = pd.DataFrame({'key1': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
'key2': [2000, 2001, 2002, 2001, 2002],
'data': np.arange(5.)})

In [329]:
lefth

key1  key2  data
0    Ohio  2000   0.0
1    Ohio  2001   1.0
2    Ohio  2002   2.0
3  Nevada  2001   3.0
4  Nevada  2002   4.0

In [330]:
righth = pd.DataFrame(np.arange(12).reshape((6, 2)),
index=[['Nevada', 'Nevada', 'Ohio', 'Ohio', 'Ohio', 'Ohio'],
[2001, 2000, 2000, 2000, 2001, 2002]],
columns=['event1', 'event2'])

In [331]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [332]:
pd.merge(lefth, righth, left_on=['key1', 'key2'], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000   0.0       4       5
0    Ohio  2000   0.0       6       7
1    Ohio  2001   1.0       8       9
2    Ohio  2002   2.0      10      11
3  Nevada  2001   3.0       0       1