In [ ]:
#Numpy
it is used for linear algebra purpose
it has binding to c libraries
to create array, vector(1d), matrices(2d), higher dimesnions and do some operations them

In [6]:
import numpy as np

In [2]:
list1=[1,3,2]

In [5]:
list1

[1, 3, 2]

In [7]:
nparr1=np.array(list1)

In [8]:
nparr1

array([1, 3, 2])

In [9]:
list2=[[1,2,3],[4,5,6],[7,8,9]]

In [10]:
list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
nparr2d = np.array(list2)

In [12]:
nparr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
'''arange function - np.arange(start, stop, step)->create array whose first element is start and last element is less than stop
and in between of consecutive elements there is difference of step'''

'arange function - np.arange(start, stop, step)->create array whose first element is start and last element is less than stop\nand in between of consecutive elements there is difference of step'

In [15]:
nparr1 = np.arange(1,10,1)

In [16]:
nparr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
r1=range(1,20,1)

In [20]:
r1

range(1, 20)

In [22]:
tuple(r1)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [25]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
'''
linspace:- np.linspace(start, end_value, no_of_values) the first value of array is start and the last value of  array is end
and total no of elements in our array is no_of_values such that there is equivalent distance between every consecutive elements
'''

'\nlinspace:- np.linspace(start, end_value, no_of_values)\n'

In [29]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [38]:
np.arange(0,10,4)

array([0, 4, 8])

In [37]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(5,5)

array([[0.68135753, 0.25064871, 0.88895719, 0.32189173, 0.52224768],
       [0.33757558, 0.77102421, 0.07161526, 0.4386699 , 0.64394587],
       [0.37094685, 0.48125328, 0.01516936, 0.14972716, 0.3244399 ],
       [0.47091222, 0.64269118, 0.29915737, 0.92178953, 0.87524016],
       [0.39115188, 0.8307965 , 0.6412765 , 0.33770797, 0.00346556]])

In [36]:
np.random.randint(1,1000)

841

In [40]:
np.random.randint(1,1000,(10,10))

array([[551, 445, 626,  27, 808,  79, 935, 981, 405, 560],
       [554, 465, 432, 307, 305, 353, 469, 196, 102, 701],
       [948, 516,  67, 695, 289, 358, 903, 480, 381, 574],
       [ 84, 747, 552, 457, 497, 678, 754, 827, 339, 148],
       [838, 371, 399, 165, 946, 152, 435, 286, 646,  33],
       [491, 193,  48, 600, 795, 670, 679, 617, 971, 942],
       [853, 113, 708, 579, 898, 678, 719, 736, 461, 444],
       [743, 899, 432,  56, 681, 690, 331, 883, 329, 265],
       [211, 334, 993, 784, 539, 286, 280, 484, 181, 552],
       [129, 343,  30, 983, 308, 569,  46, 123, 708, 569]])

In [42]:
nprandarr1=np.random.randint(1,1000,100)

In [43]:
nprandarr1

array([946, 987, 889, 201, 787,  12, 598, 184, 841, 365, 867, 530, 474,
       186, 815, 521, 761, 324, 480, 320, 336, 139, 637, 529, 151, 301,
       906, 113, 786, 430, 145, 629, 273, 620, 869, 865, 693, 331, 692,
       322, 538, 354, 647, 594,  96, 980, 358, 170, 329, 261,  62, 866,
       740, 840, 114, 309, 941, 806, 183, 350, 757, 975, 879, 261, 312,
       612, 745, 910,  15, 101,  50,  36, 140, 132, 873, 374,  67, 472,
       295, 187, 991, 508, 159,  69, 339, 436, 810, 709, 269,  30, 477,
        23, 477, 752, 926,   4, 621, 367, 455, 921])

In [45]:
nprandarr1.reshape(10,10)

array([[946, 987, 889, 201, 787,  12, 598, 184, 841, 365],
       [867, 530, 474, 186, 815, 521, 761, 324, 480, 320],
       [336, 139, 637, 529, 151, 301, 906, 113, 786, 430],
       [145, 629, 273, 620, 869, 865, 693, 331, 692, 322],
       [538, 354, 647, 594,  96, 980, 358, 170, 329, 261],
       [ 62, 866, 740, 840, 114, 309, 941, 806, 183, 350],
       [757, 975, 879, 261, 312, 612, 745, 910,  15, 101],
       [ 50,  36, 140, 132, 873, 374,  67, 472, 295, 187],
       [991, 508, 159,  69, 339, 436, 810, 709, 269,  30],
       [477,  23, 477, 752, 926,   4, 621, 367, 455, 921]])

In [49]:
nprandarr1.reshape(20,5)

array([[946, 987, 889, 201, 787],
       [ 12, 598, 184, 841, 365],
       [867, 530, 474, 186, 815],
       [521, 761, 324, 480, 320],
       [336, 139, 637, 529, 151],
       [301, 906, 113, 786, 430],
       [145, 629, 273, 620, 869],
       [865, 693, 331, 692, 322],
       [538, 354, 647, 594,  96],
       [980, 358, 170, 329, 261],
       [ 62, 866, 740, 840, 114],
       [309, 941, 806, 183, 350],
       [757, 975, 879, 261, 312],
       [612, 745, 910,  15, 101],
       [ 50,  36, 140, 132, 873],
       [374,  67, 472, 295, 187],
       [991, 508, 159,  69, 339],
       [436, 810, 709, 269,  30],
       [477,  23, 477, 752, 926],
       [  4, 621, 367, 455, 921]])

In [51]:
nprandarr1.max()

991

In [52]:
nprandarr1.min()

4

In [53]:
nprandarr1

array([946, 987, 889, 201, 787,  12, 598, 184, 841, 365, 867, 530, 474,
       186, 815, 521, 761, 324, 480, 320, 336, 139, 637, 529, 151, 301,
       906, 113, 786, 430, 145, 629, 273, 620, 869, 865, 693, 331, 692,
       322, 538, 354, 647, 594,  96, 980, 358, 170, 329, 261,  62, 866,
       740, 840, 114, 309, 941, 806, 183, 350, 757, 975, 879, 261, 312,
       612, 745, 910,  15, 101,  50,  36, 140, 132, 873, 374,  67, 472,
       295, 187, 991, 508, 159,  69, 339, 436, 810, 709, 269,  30, 477,
        23, 477, 752, 926,   4, 621, 367, 455, 921])

In [54]:
nprandarr1.argmax()

80

In [55]:
nprandarr1.argmin()

95

In [56]:
nprandarr1.mean()

479.29

In [57]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_

In [58]:
nprandarr1

array([946, 987, 889, 201, 787,  12, 598, 184, 841, 365, 867, 530, 474,
       186, 815, 521, 761, 324, 480, 320, 336, 139, 637, 529, 151, 301,
       906, 113, 786, 430, 145, 629, 273, 620, 869, 865, 693, 331, 692,
       322, 538, 354, 647, 594,  96, 980, 358, 170, 329, 261,  62, 866,
       740, 840, 114, 309, 941, 806, 183, 350, 757, 975, 879, 261, 312,
       612, 745, 910,  15, 101,  50,  36, 140, 132, 873, 374,  67, 472,
       295, 187, 991, 508, 159,  69, 339, 436, 810, 709, 269,  30, 477,
        23, 477, 752, 926,   4, 621, 367, 455, 921])

In [59]:
nprandarr1[2]

889

In [60]:
nprandarr1[-1]

921

In [62]:
nparr2=nprandarr1[1:6]

In [63]:
nprandarr1

array([946, 987, 889, 201, 787,  12, 598, 184, 841, 365, 867, 530, 474,
       186, 815, 521, 761, 324, 480, 320, 336, 139, 637, 529, 151, 301,
       906, 113, 786, 430, 145, 629, 273, 620, 869, 865, 693, 331, 692,
       322, 538, 354, 647, 594,  96, 980, 358, 170, 329, 261,  62, 866,
       740, 840, 114, 309, 941, 806, 183, 350, 757, 975, 879, 261, 312,
       612, 745, 910,  15, 101,  50,  36, 140, 132, 873, 374,  67, 472,
       295, 187, 991, 508, 159,  69, 339, 436, 810, 709, 269,  30, 477,
        23, 477, 752, 926,   4, 621, 367, 455, 921])

In [64]:
nparr2

array([987, 889, 201, 787,  12])

In [65]:
nparr2[:]=-1

In [66]:
nparr2

array([-1, -1, -1, -1, -1])

In [67]:
nprandarr1

array([946,  -1,  -1,  -1,  -1,  -1, 598, 184, 841, 365, 867, 530, 474,
       186, 815, 521, 761, 324, 480, 320, 336, 139, 637, 529, 151, 301,
       906, 113, 786, 430, 145, 629, 273, 620, 869, 865, 693, 331, 692,
       322, 538, 354, 647, 594,  96, 980, 358, 170, 329, 261,  62, 866,
       740, 840, 114, 309, 941, 806, 183, 350, 757, 975, 879, 261, 312,
       612, 745, 910,  15, 101,  50,  36, 140, 132, 873, 374,  67, 472,
       295, 187, 991, 508, 159,  69, 339, 436, 810, 709, 269,  30, 477,
        23, 477, 752, 926,   4, 621, 367, 455, 921])

In [68]:
nparr2=nprandarr1[1:6].copy()

In [69]:
nparr2

array([-1, -1, -1, -1, -1])

In [70]:
nparr2[:]=-100

In [71]:
nparr2

array([-100, -100, -100, -100, -100])

In [72]:
nprandarr1

array([946,  -1,  -1,  -1,  -1,  -1, 598, 184, 841, 365, 867, 530, 474,
       186, 815, 521, 761, 324, 480, 320, 336, 139, 637, 529, 151, 301,
       906, 113, 786, 430, 145, 629, 273, 620, 869, 865, 693, 331, 692,
       322, 538, 354, 647, 594,  96, 980, 358, 170, 329, 261,  62, 866,
       740, 840, 114, 309, 941, 806, 183, 350, 757, 975, 879, 261, 312,
       612, 745, 910,  15, 101,  50,  36, 140, 132, 873, 374,  67, 472,
       295, 187, 991, 508, 159,  69, 339, 436, 810, 709, 269,  30, 477,
        23, 477, 752, 926,   4, 621, 367, 455, 921])

In [75]:
nparr2=nprandarr1.reshape(10,10)

In [76]:
nparr2

array([[946,  -1,  -1,  -1,  -1,  -1, 598, 184, 841, 365],
       [867, 530, 474, 186, 815, 521, 761, 324, 480, 320],
       [336, 139, 637, 529, 151, 301, 906, 113, 786, 430],
       [145, 629, 273, 620, 869, 865, 693, 331, 692, 322],
       [538, 354, 647, 594,  96, 980, 358, 170, 329, 261],
       [ 62, 866, 740, 840, 114, 309, 941, 806, 183, 350],
       [757, 975, 879, 261, 312, 612, 745, 910,  15, 101],
       [ 50,  36, 140, 132, 873, 374,  67, 472, 295, 187],
       [991, 508, 159,  69, 339, 436, 810, 709, 269,  30],
       [477,  23, 477, 752, 926,   4, 621, 367, 455, 921]])

In [77]:
#for accessing the 2 more dimensions two formats are available
#double bracket

In [80]:
nparr2[1][2]

474

In [81]:
#single bracket format

In [82]:
nparr2[1,2]

474

In [83]:
nparr2

array([[946,  -1,  -1,  -1,  -1,  -1, 598, 184, 841, 365],
       [867, 530, 474, 186, 815, 521, 761, 324, 480, 320],
       [336, 139, 637, 529, 151, 301, 906, 113, 786, 430],
       [145, 629, 273, 620, 869, 865, 693, 331, 692, 322],
       [538, 354, 647, 594,  96, 980, 358, 170, 329, 261],
       [ 62, 866, 740, 840, 114, 309, 941, 806, 183, 350],
       [757, 975, 879, 261, 312, 612, 745, 910,  15, 101],
       [ 50,  36, 140, 132, 873, 374,  67, 472, 295, 187],
       [991, 508, 159,  69, 339, 436, 810, 709, 269,  30],
       [477,  23, 477, 752, 926,   4, 621, 367, 455, 921]])

In [85]:
nparr2[1:5, 2:5]

array([[474, 186, 815],
       [637, 529, 151],
       [273, 620, 869],
       [647, 594,  96]])

In [89]:
nprandarr1

array([946,  -1,  -1,  -1,  -1,  -1, 598, 184, 841, 365, 867, 530, 474,
       186, 815, 521, 761, 324, 480, 320, 336, 139, 637, 529, 151, 301,
       906, 113, 786, 430, 145, 629, 273, 620, 869, 865, 693, 331, 692,
       322, 538, 354, 647, 594,  96, 980, 358, 170, 329, 261,  62, 866,
       740, 840, 114, 309, 941, 806, 183, 350, 757, 975, 879, 261, 312,
       612, 745, 910,  15, 101,  50,  36, 140, 132, 873, 374,  67, 472,
       295, 187, 991, 508, 159,  69, 339, 436, 810, 709, 269,  30, 477,
        23, 477, 752, 926,   4, 621, 367, 455, 921])

In [90]:
boolarray=nprandarr1>500

In [91]:
boolarray

array([ True, False, False, False, False, False,  True, False,  True,
       False,  True,  True, False, False,  True,  True,  True, False,
       False, False, False, False,  True,  True, False, False,  True,
       False,  True, False, False,  True, False,  True,  True,  True,
        True, False,  True, False,  True, False,  True,  True, False,
        True, False, False, False, False, False,  True,  True,  True,
       False, False,  True,  True, False, False,  True,  True,  True,
       False, False,  True,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False,  True,
        True, False, False, False, False,  True,  True, False, False,
       False, False, False,  True,  True, False,  True, False, False,
        True])

In [92]:
nprandarr1[boolarray]

array([946, 598, 841, 867, 530, 815, 521, 761, 637, 529, 906, 786, 629,
       620, 869, 865, 693, 692, 538, 647, 594, 980, 866, 740, 840, 941,
       806, 757, 975, 879, 612, 745, 910, 873, 991, 508, 810, 709, 752,
       926, 621, 921])

In [93]:
nprandarr1[nprandarr1>500]

array([946, 598, 841, 867, 530, 815, 521, 761, 637, 529, 906, 786, 629,
       620, 869, 865, 693, 692, 538, 647, 594, 980, 866, 740, 840, 941,
       806, 757, 975, 879, 612, 745, 910, 873, 991, 508, 810, 709, 752,
       926, 621, 921])

In [94]:
nparr1= np.arange(0,21)

In [95]:
nparr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [96]:
nparr1+nparr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [97]:
nparr1*nparr1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [98]:
nparr1/nparr1

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [99]:
nparr1.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [100]:
0/0

ZeroDivisionError: division by zero

In [101]:
np.sqrt(nparr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595])

In [102]:
np.exp(nparr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08,
       4.85165195e+08])

In [104]:
'''
Pandas:-(Series, DataFrame)
it is built on Numpy
used for data cleaning or preppration
faster and productive
'''

'\nPandas:-(Series, DataFrame)\nit is built on Numpy\nused for data cleaning or preppration\nfaster and productive\n'

In [105]:
#Series:- 1d datastrucure with the row labels which could be user defined

In [106]:
import pandas as pd

In [107]:
list1=[1,2,3]

In [111]:
ser1=pd.Series(list1)

In [112]:
ser1

0    1
1    2
2    3
dtype: int64

In [113]:
ser1[1]

2

In [109]:
label1 = ['a', 'b', 'c']

In [114]:
ser2=pd.Series(data=list1, index=label1)

In [115]:
ser2

a    1
b    2
c    3
dtype: int64

In [116]:
ser2['b']

2

In [118]:
ser3=pd.Series(data=[4,5,7], index=['a','b','c'])

In [119]:
ser3

a    4
b    5
c    7
dtype: int64

In [122]:
ser2

a    1
b    2
c    3
dtype: int64

In [121]:
ser2+ser3

a     5
b     7
c    10
dtype: int64

In [123]:
ser3=pd.Series(data=[4,5,8], index=['a','b','d'])

In [125]:
ser3

a    4
b    5
d    8
dtype: int64

In [124]:
ser2+ser3

a    5.0
b    7.0
c    NaN
d    NaN
dtype: float64

In [127]:
#DataFrame:- its tabular data structure with user defined columns and row labels

In [130]:
np1=np.random.rand(5,5)

In [131]:
np1

array([[0.61618292, 0.57718986, 0.99886174, 0.31856756, 0.20823909],
       [0.25485187, 0.10595961, 0.25826019, 0.95177003, 0.5576866 ],
       [0.89611661, 0.16302832, 0.12959212, 0.2707164 , 0.97565986],
       [0.26092028, 0.88301109, 0.46002559, 0.29453712, 0.45668579],
       [0.77207715, 0.82981938, 0.45266993, 0.77374651, 0.23465216]])

In [180]:
df1=pd.DataFrame(np1, 'a b c d e'.split(), 'v w x y z'.split())

In [135]:
df1

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
b  0.254852  0.105960  0.258260  0.951770  0.557687
c  0.896117  0.163028  0.129592  0.270716  0.975660
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [136]:
df1['w']

a    0.577190
b    0.105960
c    0.163028
d    0.883011
e    0.829819
Name: w, dtype: float64

In [137]:
df1.w

a    0.577190
b    0.105960
c    0.163028
d    0.883011
e    0.829819
Name: w, dtype: float64

In [138]:
df1[['w', 'y']]

w         y
a  0.577190  0.318568
b  0.105960  0.951770
c  0.163028  0.270716
d  0.883011  0.294537
e  0.829819  0.773747

In [139]:
df1['newcol']=df1['w']+df1['y']

In [140]:
df1

v         w         x         y         z    newcol
a  0.616183  0.577190  0.998862  0.318568  0.208239  0.895757
b  0.254852  0.105960  0.258260  0.951770  0.557687  1.057730
c  0.896117  0.163028  0.129592  0.270716  0.975660  0.433745
d  0.260920  0.883011  0.460026  0.294537  0.456686  1.177548
e  0.772077  0.829819  0.452670  0.773747  0.234652  1.603566

In [142]:
df1.drop('newcol', axis=1)

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
b  0.254852  0.105960  0.258260  0.951770  0.557687
c  0.896117  0.163028  0.129592  0.270716  0.975660
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [143]:
df1

v         w         x         y         z    newcol
a  0.616183  0.577190  0.998862  0.318568  0.208239  0.895757
b  0.254852  0.105960  0.258260  0.951770  0.557687  1.057730
c  0.896117  0.163028  0.129592  0.270716  0.975660  0.433745
d  0.260920  0.883011  0.460026  0.294537  0.456686  1.177548
e  0.772077  0.829819  0.452670  0.773747  0.234652  1.603566

In [144]:
df1.drop('newcol', axis=1, inplace=True)

In [145]:
df1

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
b  0.254852  0.105960  0.258260  0.951770  0.557687
c  0.896117  0.163028  0.129592  0.270716  0.975660
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [147]:
df1.drop('c', axis=0)

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
b  0.254852  0.105960  0.258260  0.951770  0.557687
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [148]:
df1

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
b  0.254852  0.105960  0.258260  0.951770  0.557687
c  0.896117  0.163028  0.129592  0.270716  0.975660
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [149]:
df1.shape

(5, 5)

In [150]:
#Selecting row
#loc method
#iloc method

In [152]:
df1.loc['b']

v    0.254852
w    0.105960
x    0.258260
y    0.951770
z    0.557687
Name: b, dtype: float64

In [153]:
df1.iloc[1]

v    0.254852
w    0.105960
x    0.258260
y    0.951770
z    0.557687
Name: b, dtype: float64

In [154]:
df1.loc['b', 'y']

0.9517700265063176

In [156]:
df1.loc['b']['y']

0.9517700265063176

In [157]:
df1.loc[['b', 'd'],['w', 'y']]

w         y
b  0.105960  0.951770
d  0.883011  0.294537

In [158]:
df1

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
b  0.254852  0.105960  0.258260  0.951770  0.557687
c  0.896117  0.163028  0.129592  0.270716  0.975660
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [160]:
booldf=df1['w']>0.5

In [161]:
booldf

a     True
b    False
c    False
d     True
e     True
Name: w, dtype: bool

In [162]:
df1[booldf]

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [163]:
df1[df1['w']>0.5]

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [164]:
df1

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
b  0.254852  0.105960  0.258260  0.951770  0.557687
c  0.896117  0.163028  0.129592  0.270716  0.975660
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [166]:
(df1['w']>0.5) & (df1['x']<0.5)

a    False
b    False
c    False
d     True
e     True
dtype: bool

In [171]:
df1[(df1['w']>0.5) & (df1['x']<0.5)]

v         w         x         y         z
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [172]:
df1[(df1['w']>0.5) & (df1['x']<0.5)][['y', 'z']]

y         z
d  0.294537  0.456686
e  0.773747  0.234652

In [173]:
df1

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
b  0.254852  0.105960  0.258260  0.951770  0.557687
c  0.896117  0.163028  0.129592  0.270716  0.975660
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [174]:
df1.reset_index()

index         v         w         x         y         z
0     a  0.616183  0.577190  0.998862  0.318568  0.208239
1     b  0.254852  0.105960  0.258260  0.951770  0.557687
2     c  0.896117  0.163028  0.129592  0.270716  0.975660
3     d  0.260920  0.883011  0.460026  0.294537  0.456686
4     e  0.772077  0.829819  0.452670  0.773747  0.234652

In [175]:
df1

v         w         x         y         z
a  0.616183  0.577190  0.998862  0.318568  0.208239
b  0.254852  0.105960  0.258260  0.951770  0.557687
c  0.896117  0.163028  0.129592  0.270716  0.975660
d  0.260920  0.883011  0.460026  0.294537  0.456686
e  0.772077  0.829819  0.452670  0.773747  0.234652

In [176]:
df1.reset_index(inplace=True)

In [177]:
df1

index         v         w         x         y         z
0     a  0.616183  0.577190  0.998862  0.318568  0.208239
1     b  0.254852  0.105960  0.258260  0.951770  0.557687
2     c  0.896117  0.163028  0.129592  0.270716  0.975660
3     d  0.260920  0.883011  0.460026  0.294537  0.456686
4     e  0.772077  0.829819  0.452670  0.773747  0.234652

In [178]:
df1.drop('index', axis=1, inplace=True)

In [179]:
df1

v         w         x         y         z
0  0.616183  0.577190  0.998862  0.318568  0.208239
1  0.254852  0.105960  0.258260  0.951770  0.557687
2  0.896117  0.163028  0.129592  0.270716  0.975660
3  0.260920  0.883011  0.460026  0.294537  0.456686
4  0.772077  0.829819  0.452670  0.773747  0.234652

In [181]:
df1=pd.DataFrame(np1, 'a b c d e'.split(), 'v w x y z'.split())

In [183]:
df1.reset_index(inplace=True)

In [184]:
df1

index         v         w         x         y         z
0     a  0.616183  0.577190  0.998862  0.318568  0.208239
1     b  0.254852  0.105960  0.258260  0.951770  0.557687
2     c  0.896117  0.163028  0.129592  0.270716  0.975660
3     d  0.260920  0.883011  0.460026  0.294537  0.456686
4     e  0.772077  0.829819  0.452670  0.773747  0.234652

In [187]:
df1.set_index('index', inplace=True)

In [188]:
df1

v         w         x         y         z
index                                                  
a      0.616183  0.577190  0.998862  0.318568  0.208239
b      0.254852  0.105960  0.258260  0.951770  0.557687
c      0.896117  0.163028  0.129592  0.270716  0.975660
d      0.260920  0.883011  0.460026  0.294537  0.456686
e      0.772077  0.829819  0.452670  0.773747  0.234652

In [189]:
dict1 = {'A':[1,2,np.nan], 'B':[12, np.nan, np.nan], 'c':[3,5,10]}

In [190]:
dict1

{'A': [1, 2, nan], 'B': [12, nan, nan], 'c': [3, 5, 10]}

In [191]:
df2=pd.DataFrame(dict1)

In [192]:
df2

A     B   c
0  1.0  12.0   3
1  2.0   NaN   5
2  NaN   NaN  10

In [193]:
#removing rows with null values
df2.dropna()

A     B  c
0  1.0  12.0  3

In [194]:
df2

A     B   c
0  1.0  12.0   3
1  2.0   NaN   5
2  NaN   NaN  10

In [195]:
#removing columns with null values
df2.dropna(axis=1)

c
0   3
1   5
2  10

In [196]:
df2

A     B   c
0  1.0  12.0   3
1  2.0   NaN   5
2  NaN   NaN  10

In [198]:
df2.dropna(thresh=2)# remove those rows where non null value are less than 2

A     B  c
0  1.0  12.0  3
1  2.0   NaN  5

In [199]:
df2

A     B   c
0  1.0  12.0   3
1  2.0   NaN   5
2  NaN   NaN  10

In [206]:
df2.fillna(value='as')

A   B   c
0   1  12   3
1   2  as   5
2  as  as  10

In [201]:
df2

A     B   c
0  1.0  12.0   3
1  2.0   NaN   5
2  NaN   NaN  10

In [204]:
df2['A'].fillna(value=df2['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

In [205]:
df2

A     B   c
0  1.0  12.0   3
1  2.0   NaN   5
2  NaN   NaN  10

In [207]:
df2.columns

Index(['A', 'B', 'c'], dtype='object')