In [1]:
def empname(name):
    return name


In [2]:
empname("victor")

'victor'

In [3]:
def addnums(num1,num2):
    sum = num1+num2
    return sum

In [4]:
addnums(200,300)

500

In [5]:
addnums(200,"hello")

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [6]:
def myfunc(x):
    if(x == "MrRight"):
        print("welcome")
    else:
        print("you are not authorized")

In [7]:
myfunc("john")

you are not authorized


In [8]:
first = "queen"
last = "elizabeth"

In [9]:
first

'queen'

In [10]:
last

'elizabeth'

In [11]:
msg = first + ' [' + last + '] is a queen' 

In [12]:
msg

'queen [elizabeth] is a queen'

In [13]:
msgf = f'{first} {last} is a queen'

In [14]:
msgf

'queen elizabeth is a queen'

In [15]:
def greet_user():
    print("hi there!")
    print("welcome aboard!")


In [16]:
print("start")


start


In [17]:
greet_user()

hi there!
welcome aboard!


In [18]:
def greet_user2(name):
    print(f'Hi {name}!')
    print('Welcome aboard')

In [19]:
greet_user2("peter")

Hi peter!
Welcome aboard


In [20]:
def greet_user3(fname,lname):
    print(f'Hi {fname} {lname}!')
    print('Welcome aboard')

In [21]:
greet_user3("patrick","sean")

Hi patrick sean!
Welcome aboard


In [22]:
greet_user3(lname="john",fname="smith")

Hi smith john!
Welcome aboard


In [24]:
greet_user3("smith",lname="johny")

Hi smith johny!
Welcome aboard


In [25]:
greet_user3("smith",fname="johny")

TypeError: greet_user3() got multiple values for argument 'fname'

In [26]:
greet_user3(lname="johny","smith")

SyntaxError: positional argument follows keyword argument (<ipython-input-26-0946c9d97dfc>, line 1)

In [27]:
nums = [23,34,45,56,67,78]

In [28]:
type(nums)

list

In [31]:
def mult(num):
    return num * 10

In [32]:
mult(2)

20

In [34]:
for i in nums:
    x = mult(i)
    print(x)

230
340
450
560
670
780


In [35]:
nums

[23, 34, 45, 56, 67, 78]

In [36]:
y = map(lambda u: u * 10,nums)

In [37]:
y

In [38]:
for i in y:
    print(i)

230
340
450
560
670
780


In [39]:
friends = ['mary','peter','aj','patrick','susie']

In [40]:
FRIENDS = map(lambda o : o.upper(),friends)

In [42]:
for i in FRIENDS:
    print(i)

MARY
PETER
AJ
PATRICK
SUSIE


In [43]:
nums

[23, 34, 45, 56, 67, 78]

In [54]:
usingfilter = list(filter(lambda n: n%2==0,nums))

In [55]:
for i in usingfilter:
    print(i)

34
56
78


In [56]:
nums

[23, 34, 45, 56, 67, 78]

In [59]:
from functools import reduce
usingreduce = reduce((lambda x,y: x+y),nums)

In [60]:
print(usingreduce)

303


In [61]:
friends

['mary', 'peter', 'aj', 'patrick', 'susie']

In [62]:
for i in friends:
    print(i,friends.index(i))

mary 0
peter 1
aj 2
patrick 3
susie 4


In [63]:
#using enumerate func
for iposition,name in enumerate(friends):
    print(iposition,name)

0 mary
1 peter
2 aj
3 patrick
4 susie


In [65]:
store_a_map = dict((name,position) for position,name in enumerate(friends))

In [66]:
type(store_a_map)

dict

In [67]:
store_a_map

{'mary': 0, 'peter': 1, 'aj': 2, 'patrick': 3, 'susie': 4}

In [69]:
store_a_map.keys()


dict_keys(['mary', 'peter', 'aj', 'patrick', 'susie'])

In [70]:
store_a_map.values()

dict_values([0, 1, 2, 3, 4])

In [71]:
marks_list = range(10)

In [72]:
marks_list

range(0, 10)

In [74]:
for i in marks_list:
    print(i,end=",")

0,1,2,3,4,5,6,7,8,9,

In [75]:
semmarks_list = range(1,100
                    )

In [76]:
for i in semmarks_list:
    print(i,end=":")

1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20:21:22:23:24:25:26:27:28:29:30:31:32:33:34:35:36:37:38:39:40:41:42:43:44:45:46:47:48:49:50:51:52:53:54:55:56:57:58:59:60:61:62:63:64:65:66:67:68:69:70:71:72:73:74:75:76:77:78:79:80:81:82:83:84:85:86:87:88:89:90:91:92:93:94:95:96:97:98:99:

In [77]:
type(marks_list)

range

In [78]:
type(semmarks_list)

range

In [79]:
list_of_marks = list(reversed(marks_list))

In [80]:
list_of_marks

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [81]:
marks_list

range(0, 10)

In [82]:
markslist = list(marks_list)


In [83]:
markslist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
list_of_marks

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [85]:
zippedresult = zip(markslist,list_of_marks)

In [89]:
for i in zippedresult:
    print(i)

(0, 9)
(1, 8)
(2, 7)
(3, 6)
(4, 5)
(5, 4)
(6, 3)
(7, 2)
(8, 1)
(9, 0)


In [90]:
type(zippedresult)

zip

In [91]:
x = 100

In [97]:
y = int(input("enter a number: "))
if y > x :
    print("you entered a number not acceptable")
elif y==x:
    print("cool, you got number as wanted")
else:
    print("cool, you are still within limits")

enter a number:  100


cool, you got number as wanted


In [98]:
friends

['mary', 'peter', 'aj', 'patrick', 'susie']

In [99]:
bestfriends = []
for i in friends:
    if i!='aj':
        bestfriends.append(i)
        

In [100]:
bestfriends

['mary', 'peter', 'patrick', 'susie']

In [101]:
len(friends)

5

In [102]:
for i in range(0,len(friends)):
    print(i)

0
1
2
3
4


In [105]:
try:
    age = int(input('Age:'))
    income = 20000
    risk = income/age
    print(risk)
except ZeroDivisionError:
    print('Age cannot be 0')
except ValueError:
    print('Invalid value')

Age: hello


Invalid value


In [106]:
distance = [10,15,17,24]

In [107]:
time = [.30,.47,.55,1.20]

In [109]:
import numpy as np

In [114]:
np1 = np.array(distance)

In [113]:
np2 = np.array(time)

In [115]:
type(np1)

numpy.ndarray

In [116]:
speed = np1/np2

In [118]:
speed

array([33.33333333, 31.91489362, 30.90909091, 20.        ])

In [119]:
for i in speed:
    print(i)

33.333333333333336
31.914893617021278
30.909090909090907
20.0


In [120]:
first_numpy_array = np.array([1,3,5,7])

In [121]:
first_numpy_array

array([1, 3, 5, 7])

In [122]:
array_with_zeroes = np.zeros((3,3))

In [123]:
array_with_zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
array_with_ones = np.ones((3,3))

In [125]:
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [126]:
array_with_empty = np.empty((2,3))

In [127]:
array_with_empty

array([[4.67528219e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [128]:
np_arange = np.arange(12)

In [129]:
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [135]:
listx = [23,34,45]

In [136]:
arrtest = np.array(listx)

In [137]:
type(arrtest)

numpy.ndarray

In [138]:
arrtest

array([23, 34, 45])

In [139]:
listy = [100,200,300]

In [141]:
arrtest2 = np.array([listx,listy])

In [142]:
arrtest2

array([[ 23,  34,  45],
       [100, 200, 300]])

In [143]:
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [144]:
np_arange.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [145]:
np_arange.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [146]:
np_arange.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [147]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
#one dimensional array
oneD_array = np.arange(15)

In [149]:
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [150]:
oneD_array.ndim

1

In [151]:
oneD_array.shape

(15,)

In [152]:
oneD_array.size

15

In [153]:
twoD_array = oneD_array.reshape(3,5)

In [154]:
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [155]:
type(twoD_array)

numpy.ndarray

In [156]:
twoD_array.dtype

dtype('int64')

In [165]:
oneDnew_array = np.arange(27)


In [163]:
oneDnew_array

array(27)

In [166]:
threeD_array = oneDnew_array.reshape(3,3,3)

In [167]:
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [171]:
print(threeD_array.ndim,
threeD_array.shape,
threeD_array.size,
threeD_array.dtype)

3 (3, 3, 3) 27 int64


In [172]:
first_trial_cyclist = [10,15,17,24]

In [173]:
second_trial_cyclist = [12,11,21,24]

In [174]:
np_first_trial_cyclist = np.array(first_trial_cyclist)

In [175]:
np_second_trial_cylist = np.array(second_trial_cyclist)

In [176]:
result = np_first_trial_cyclist+np_second_trial_cylist

In [177]:
result

array([22, 26, 38, 48])

In [178]:
np.add(45,20)

65

In [179]:
np_daily_wage = np.array([7,8,9,11,13])*45

In [180]:
np_daily_wage

array([315, 360, 405, 495, 585])

In [181]:
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [182]:
oneD_array[0:3]

array([0, 1, 2])

In [189]:
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [190]:
twoD_array[0:2,0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [195]:
twoD_array[0][3]

3

In [193]:
twoD_array[2][0]

10

In [196]:
modtwoD_array = twoD_array[:,0:2]

In [197]:
modtwoD_array

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [199]:
x = [23,34,23,43]

In [200]:
day1 = x * 6

In [202]:
len(day1)

24

In [203]:
day2 = x * 6

In [204]:
len(day2)

24

In [205]:
print(day1, end=" ")

[23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43] 

In [206]:
print(day2, end = " ")

[23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43] 

In [208]:
day1info = np.array(day1)

In [209]:
day1info

array([23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23,
       34, 23, 43, 23, 34, 23, 43])

In [210]:
day1info[day1info > 33]

array([34, 43, 34, 43, 34, 43, 34, 43, 34, 43, 34, 43])

In [211]:
day1infoup = day1info > 33

In [212]:
day1infoup

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])