In [1]:
def empname(name):
    return name


In [2]:
empname("victor")

'victor'

In [3]:
def addnums(num1,num2):
    sum = num1+num2
    return sum

In [4]:
addnums(200,300)

500

In [5]:
addnums(200,"hello")

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [6]:
def myfunc(x):
    if(x == "MrRight"):
        print("welcome")
    else:
        print("you are not authorized")

In [7]:
myfunc("john")

you are not authorized


In [8]:
first = "queen"
last = "elizabeth"

In [9]:
first

'queen'

In [10]:
last

'elizabeth'

In [11]:
msg = first + ' [' + last + '] is a queen' 

In [12]:
msg

'queen [elizabeth] is a queen'

In [13]:
msgf = f'{first} {last} is a queen'

In [14]:
msgf

'queen elizabeth is a queen'

In [15]:
def greet_user():
    print("hi there!")
    print("welcome aboard!")


In [16]:
print("start")


start


In [17]:
greet_user()

hi there!
welcome aboard!


In [18]:
def greet_user2(name):
    print(f'Hi {name}!')
    print('Welcome aboard')

In [19]:
greet_user2("peter")

Hi peter!
Welcome aboard


In [20]:
def greet_user3(fname,lname):
    print(f'Hi {fname} {lname}!')
    print('Welcome aboard')

In [21]:
greet_user3("patrick","sean")

Hi patrick sean!
Welcome aboard


In [22]:
greet_user3(lname="john",fname="smith")

Hi smith john!
Welcome aboard


In [24]:
greet_user3("smith",lname="johny")

Hi smith johny!
Welcome aboard


In [25]:
greet_user3("smith",fname="johny")

TypeError: greet_user3() got multiple values for argument 'fname'

In [26]:
greet_user3(lname="johny","smith")

SyntaxError: positional argument follows keyword argument (<ipython-input-26-0946c9d97dfc>, line 1)

In [27]:
nums = [23,34,45,56,67,78]

In [28]:
type(nums)

list

In [31]:
def mult(num):
    return num * 10

In [32]:
mult(2)

20

In [34]:
for i in nums:
    x = mult(i)
    print(x)

230
340
450
560
670
780


In [35]:
nums

[23, 34, 45, 56, 67, 78]

In [36]:
y = map(lambda u: u * 10,nums)

In [37]:
y

In [38]:
for i in y:
    print(i)

230
340
450
560
670
780


In [39]:
friends = ['mary','peter','aj','patrick','susie']

In [40]:
FRIENDS = map(lambda o : o.upper(),friends)

In [42]:
for i in FRIENDS:
    print(i)

MARY
PETER
AJ
PATRICK
SUSIE


In [43]:
nums

[23, 34, 45, 56, 67, 78]

In [54]:
usingfilter = list(filter(lambda n: n%2==0,nums))

In [55]:
for i in usingfilter:
    print(i)

34
56
78


In [56]:
nums

[23, 34, 45, 56, 67, 78]

In [59]:
from functools import reduce
usingreduce = reduce((lambda x,y: x+y),nums)

In [60]:
print(usingreduce)

303


In [61]:
friends

['mary', 'peter', 'aj', 'patrick', 'susie']

In [62]:
for i in friends:
    print(i,friends.index(i))

mary 0
peter 1
aj 2
patrick 3
susie 4


In [63]:
#using enumerate func
for iposition,name in enumerate(friends):
    print(iposition,name)

0 mary
1 peter
2 aj
3 patrick
4 susie


In [65]:
store_a_map = dict((name,position) for position,name in enumerate(friends))

In [66]:
type(store_a_map)

dict

In [67]:
store_a_map

{'mary': 0, 'peter': 1, 'aj': 2, 'patrick': 3, 'susie': 4}

In [69]:
store_a_map.keys()


dict_keys(['mary', 'peter', 'aj', 'patrick', 'susie'])

In [70]:
store_a_map.values()

dict_values([0, 1, 2, 3, 4])

In [71]:
marks_list = range(10)

In [72]:
marks_list

range(0, 10)

In [74]:
for i in marks_list:
    print(i,end=",")

0,1,2,3,4,5,6,7,8,9,

In [75]:
semmarks_list = range(1,100
                    )

In [76]:
for i in semmarks_list:
    print(i,end=":")

1:2:3:4:5:6:7:8:9:10:11:12:13:14:15:16:17:18:19:20:21:22:23:24:25:26:27:28:29:30:31:32:33:34:35:36:37:38:39:40:41:42:43:44:45:46:47:48:49:50:51:52:53:54:55:56:57:58:59:60:61:62:63:64:65:66:67:68:69:70:71:72:73:74:75:76:77:78:79:80:81:82:83:84:85:86:87:88:89:90:91:92:93:94:95:96:97:98:99:

In [77]:
type(marks_list)

range

In [78]:
type(semmarks_list)

range

In [79]:
list_of_marks = list(reversed(marks_list))

In [80]:
list_of_marks

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [81]:
marks_list

range(0, 10)

In [82]:
markslist = list(marks_list)


In [83]:
markslist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [84]:
list_of_marks

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [85]:
zippedresult = zip(markslist,list_of_marks)

In [89]:
for i in zippedresult:
    print(i)

(0, 9)
(1, 8)
(2, 7)
(3, 6)
(4, 5)
(5, 4)
(6, 3)
(7, 2)
(8, 1)
(9, 0)


In [90]:
type(zippedresult)

zip

In [91]:
x = 100

In [97]:
y = int(input("enter a number: "))
if y > x :
    print("you entered a number not acceptable")
elif y==x:
    print("cool, you got number as wanted")
else:
    print("cool, you are still within limits")

enter a number:  100


cool, you got number as wanted


In [98]:
friends

['mary', 'peter', 'aj', 'patrick', 'susie']

In [99]:
bestfriends = []
for i in friends:
    if i!='aj':
        bestfriends.append(i)
        

In [100]:
bestfriends

['mary', 'peter', 'patrick', 'susie']

In [101]:
len(friends)

5

In [102]:
for i in range(0,len(friends)):
    print(i)

0
1
2
3
4


In [105]:
try:
    age = int(input('Age:'))
    income = 20000
    risk = income/age
    print(risk)
except ZeroDivisionError:
    print('Age cannot be 0')
except ValueError:
    print('Invalid value')

Age: hello


Invalid value


In [106]:
distance = [10,15,17,24]

In [107]:
time = [.30,.47,.55,1.20]

In [109]:
import numpy as np

In [114]:
np1 = np.array(distance)

In [113]:
np2 = np.array(time)

In [115]:
type(np1)

numpy.ndarray

In [116]:
speed = np1/np2

In [118]:
speed

array([33.33333333, 31.91489362, 30.90909091, 20.        ])

In [119]:
for i in speed:
    print(i)

33.333333333333336
31.914893617021278
30.909090909090907
20.0


In [120]:
first_numpy_array = np.array([1,3,5,7])

In [121]:
first_numpy_array

array([1, 3, 5, 7])

In [122]:
array_with_zeroes = np.zeros((3,3))

In [123]:
array_with_zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
array_with_ones = np.ones((3,3))

In [125]:
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [126]:
array_with_empty = np.empty((2,3))

In [127]:
array_with_empty

array([[4.67528219e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [128]:
np_arange = np.arange(12)

In [129]:
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [135]:
listx = [23,34,45]

In [136]:
arrtest = np.array(listx)

In [137]:
type(arrtest)

numpy.ndarray

In [138]:
arrtest

array([23, 34, 45])

In [139]:
listy = [100,200,300]

In [141]:
arrtest2 = np.array([listx,listy])

In [142]:
arrtest2

array([[ 23,  34,  45],
       [100, 200, 300]])

In [143]:
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [144]:
np_arange.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [145]:
np_arange.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [146]:
np_arange.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [147]:
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
#one dimensional array
oneD_array = np.arange(15)

In [149]:
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [150]:
oneD_array.ndim

1

In [151]:
oneD_array.shape

(15,)

In [152]:
oneD_array.size

15

In [153]:
twoD_array = oneD_array.reshape(3,5)

In [154]:
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [155]:
type(twoD_array)

numpy.ndarray

In [156]:
twoD_array.dtype

dtype('int64')

In [165]:
oneDnew_array = np.arange(27)


In [163]:
oneDnew_array

array(27)

In [166]:
threeD_array = oneDnew_array.reshape(3,3,3)

In [167]:
threeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [171]:
print(threeD_array.ndim,
threeD_array.shape,
threeD_array.size,
threeD_array.dtype)

3 (3, 3, 3) 27 int64


In [172]:
first_trial_cyclist = [10,15,17,24]

In [173]:
second_trial_cyclist = [12,11,21,24]

In [174]:
np_first_trial_cyclist = np.array(first_trial_cyclist)

In [175]:
np_second_trial_cylist = np.array(second_trial_cyclist)

In [176]:
result = np_first_trial_cyclist+np_second_trial_cylist

In [177]:
result

array([22, 26, 38, 48])

In [178]:
np.add(45,20)

65

In [179]:
np_daily_wage = np.array([7,8,9,11,13])*45

In [180]:
np_daily_wage

array([315, 360, 405, 495, 585])

In [181]:
oneD_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [182]:
oneD_array[0:3]

array([0, 1, 2])

In [189]:
twoD_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [190]:
twoD_array[0:2,0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [195]:
twoD_array[0][3]

3

In [193]:
twoD_array[2][0]

10

In [196]:
modtwoD_array = twoD_array[:,0:2]

In [197]:
modtwoD_array

array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [2]:
import numpy as np
x = [23,34,23,43]

In [3]:
day1 = x * 6

In [4]:
len(day1)

24

In [5]:
day2 = x * 6

In [6]:
len(day2)

24

In [7]:
print(day1, end=" ")

[23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43] 

In [8]:
print(day2, end = " ")

[23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43] 

In [9]:
day1info = np.array(day1)

In [10]:
day1info

array([23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23, 34, 23, 43, 23,
       34, 23, 43, 23, 34, 23, 43])

In [11]:
day1info[day1info > 33]

array([34, 43, 34, 43, 34, 43, 34, 43, 34, 43, 34, 43])

In [12]:
day1infoup = day1info > 33

In [13]:
day1infoup

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [14]:
day1info[day1infoup]

array([34, 43, 34, 43, 34, 43, 34, 43, 34, 43, 34, 43])

In [15]:
friends = np.array(['mary', 'peter', 'aj', 'patrick', 'susie'])

In [16]:
friends

array(['mary', 'peter', 'aj', 'patrick', 'susie'], dtype='<U7')

In [17]:
friends.dtype

dtype('<U7')

In [18]:
friends.ndim

1

In [19]:
friends.shape

(5,)

In [20]:
friends_new = friends

In [21]:
friends

array(['mary', 'peter', 'aj', 'patrick', 'susie'], dtype='<U7')

In [22]:
friends_new

array(['mary', 'peter', 'aj', 'patrick', 'susie'], dtype='<U7')

In [23]:
friends_new is friends

True

In [24]:
nums = [23,34,45,56,67,78,89,90]

In [25]:
numsnp = np.array([nums])

In [26]:
numsnp

array([[23, 34, 45, 56, 67, 78, 89, 90]])

In [27]:
numsnp.dtype

dtype('int64')

In [28]:
numsnp2 = numsnp

In [29]:
numsnp2

array([[23, 34, 45, 56, 67, 78, 89, 90]])

In [30]:
numsnp is numsnp2

True

In [31]:
numsnp * 10

array([[230, 340, 450, 560, 670, 780, 890, 900]])

In [32]:
numsnp2

array([[23, 34, 45, 56, 67, 78, 89, 90]])

In [33]:
numsnp is numsnp2

True

In [34]:
numsnp

array([[23, 34, 45, 56, 67, 78, 89, 90]])

In [35]:
numsnp = np.array([23,34,45,56,67,78])

In [36]:
numsnp

array([23, 34, 45, 56, 67, 78])

In [37]:
numsnp2 = numsnp

In [39]:
numsnp2

array([23, 34, 45, 56, 67, 78])

In [40]:
numsnp2 is numsnp

True

In [47]:
numsnp = "hello"

In [49]:
numsnp

'hello'

In [67]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [51]:
numsnp2 is numsnp

False

In [68]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [69]:
numsnp3_vw = numsnp2.view()

In [70]:
numsnp2 is numsnp3_vw

False

In [71]:
len(numsnp2)

6

In [72]:
len(numsnp3_vw   )

6

In [73]:
numsnp3_vw[0] = 100

In [74]:
numsnp3_vw

array([100,  34,  45,  56,  67,  78])

In [75]:
numsnp2

array([100,  34,  45,  56,  67,  78])

In [76]:
numsnp2

array([100,  34,  45,  56,  67,  78])

In [77]:
numsnp2[0] = 1000

In [78]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [79]:
numsnp3_vw

array([1000,   34,   45,   56,   67,   78])

In [80]:
numsnp2 is numsnp3_vw

False

In [81]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [82]:
numsnp3_vw

array([1000,   34,   45,   56,   67,   78])

In [83]:
numsnp4 = numsnp2.copy()

In [84]:
numsnp4 is numsnp2

False

In [85]:
numsnp4

array([1000,   34,   45,   56,   67,   78])

In [86]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [87]:
numsnp4.reshape(2,3)

array([[1000,   34,   45],
       [  56,   67,   78]])

In [88]:
numsnp2

array([1000,   34,   45,   56,   67,   78])

In [89]:
numsnp2[1]= 10000

In [90]:
numsnp2

array([ 1000, 10000,    45,    56,    67,    78])

In [91]:
numsnp4

array([1000,   34,   45,   56,   67,   78])

In [92]:
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,13,14,24,14,23]])

In [93]:
new_cyclist_trials


array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [94]:
new_cyclist_trials.ndim

2

In [95]:
new_cyclist_trials.shape

(2, 6)

In [96]:
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 13],
       [14, 24, 14, 23]])

In [97]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [98]:
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [99]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [100]:
new_cyclist_trials = new_cyclist_trials.ravel()

In [101]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [103]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [104]:
new_cyclist_trials.argmax()

3

In [105]:
new_cyclist_trials.argmin()

0

In [106]:
new_cyclist_trials.ndim

1

In [107]:
new_cyclist_trials = new_cyclist_trials.reshape(3,4)

In [109]:
new_cyclist_trials

array([[10, 15, 17, 26],
       [13, 19, 12, 13],
       [14, 24, 14, 23]])

In [110]:
np.hsplit(new_cyclist_trials,2)

[array([[10, 15],
        [13, 19],
        [14, 24]]),
 array([[17, 26],
        [12, 13],
        [14, 23]])]

In [112]:
new_cyclist_trials

array([[10, 15, 17, 26],
       [13, 19, 12, 13],
       [14, 24, 14, 23]])

In [113]:
new_cyclist_trials = new_cyclist_trials.ravel()

In [114]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [115]:
new_cyclist_trials1 = new_cyclist_trials.ravel()

In [116]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [117]:
new_cyclist_trials1

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [118]:
new_cyclist_trials = new_cyclist_trials1

In [120]:
new_cyclist_trials

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [121]:
new_cyclist_trials1

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [122]:
new_cyclist_trials is new_cyclist_trials1

True

In [123]:
x = new_cyclist_trials

In [124]:
x

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [125]:
y = new_cyclist_trials

In [126]:
y

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [127]:
x is y

True

In [128]:
new_cyclist_trials1 = np.array([[10,15,17,26,13,19],[12,13,14,24,14,23]])

In [129]:
new_cyclist_trials1

array([[10, 15, 17, 26, 13, 19],
       [12, 13, 14, 24, 14, 23]])

In [130]:
new_cyclist_trials1 = new_cyclist_trials1.ravel()

In [131]:
new_cyclist_trials1

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [132]:
new_cyclist_trials2 = np.array([[10,15,17,26,13,19],[12,13,14,24,14,23]])

In [133]:
new_cyclist_trials2 = new_cyclist_trials2.ravel()

In [134]:
new_cyclist_trials2

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23])

In [138]:
stked = np.hstack((new_cyclist_trials1,new_cyclist_trials2))

In [139]:
stked

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23, 10, 15, 17, 26, 13,
       19, 12, 13, 14, 24, 14, 23])

In [140]:
stked

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23, 10, 15, 17, 26, 13,
       19, 12, 13, 14, 24, 14, 23])

In [152]:
test = list(map((lambda n: n* 100),stked))


In [153]:
test2 = sorted(test)

In [156]:
print(test2,end=",")

[1000, 1000, 1200, 1200, 1300, 1300, 1300, 1300, 1400, 1400, 1400, 1400, 1500, 1500, 1700, 1700, 1900, 1900, 2300, 2300, 2400, 2400, 2600, 2600],

In [157]:
stked

array([10, 15, 17, 26, 13, 19, 12, 13, 14, 24, 14, 23, 10, 15, 17, 26, 13,
       19, 12, 13, 14, 24, 14, 23])

In [159]:
stked * 100

array([1000, 1500, 1700, 2600, 1300, 1900, 1200, 1300, 1400, 2400, 1400,
       2300, 1000, 1500, 1700, 2600, 1300, 1900, 1200, 1300, 1400, 2400,
       1400, 2300])

In [160]:
test_data = np.array([[23,34,45,56],[34,45,56,67]])

In [161]:
test_data

array([[23, 34, 45, 56],
       [34, 45, 56, 67]])

In [162]:
test_data.transpose()

array([[23, 34],
       [34, 45],
       [45, 56],
       [56, 67]])

In [163]:
test_data

array([[23, 34, 45, 56],
       [34, 45, 56, 67]])

In [164]:
test_data = test_data.transpose()

In [165]:
test_data

array([[23, 34],
       [34, 45],
       [45, 56],
       [56, 67]])

In [166]:
A = np.array([[6,1,1],[4,-2,5],[2,8,7]])

In [167]:
A

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [168]:
np.linalg.inv(A)

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [169]:
np.linalg.matrix_rank(A)

3

In [170]:
np.trace(A)

11

In [171]:
np.linalg.det(A)

-306.0

In [172]:
countries = np.array(['luxembourg','Norway','Japan','Switzerland','USA','Qatar'])

In [173]:
gdp_per_capita = np.array([52056.1234,40345.4565,45456.78564,33245.56782,34544.45888])

In [174]:
max_gdp_per_capita = gdp_per_capita.argmax()

In [175]:
max_gdp_per_capita

0

In [178]:
country_with_max_gdp_per_capita = countries[max_gdp_per_capita]

In [179]:
country_with_max_gdp_per_capita

'luxembourg'

In [180]:
for country in countries:
    print('ecalculating country {}'.format(country))

ecalculating country luxembourg
ecalculating country Norway
ecalculating country Japan
ecalculating country Switzerland
ecalculating country USA
ecalculating country Qatar


In [181]:
for i in range(len(countries)-1):
    country = countries[i]
    country_gdp_per_capita = gdp_per_capita[i]
    print('country {} per capita gdp is {}'.format(country,country_gdp_per_capita))

country luxembourg per capita gdp is 52056.1234
country Norway per capita gdp is 40345.4565
country Japan per capita gdp is 45456.78564
country Switzerland per capita gdp is 33245.56782
country USA per capita gdp is 34544.45888


In [182]:
import pandas as pd

In [183]:
ser1 = pd.Series('welcome')

In [184]:
type(ser1)

pandas.core.series.Series

In [185]:
ser1

0    welcome
dtype: object

In [189]:
ser1 = pd.Series(['welcome','hello','cool'])

In [190]:
ser1

0    welcome
1      hello
2       cool
dtype: object

In [191]:
ser2 = pd.Series(list('abcdefgh'))

In [192]:
ser2

0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
dtype: object

In [193]:
countries

array(['luxembourg', 'Norway', 'Japan', 'Switzerland', 'USA', 'Qatar'],
      dtype='<U11')

In [194]:
cdata = pd.Series(countries)

In [195]:
cdata

0     luxembourg
1         Norway
2          Japan
3    Switzerland
4            USA
5          Qatar
dtype: object

In [196]:
countries

array(['luxembourg', 'Norway', 'Japan', 'Switzerland', 'USA', 'Qatar'],
      dtype='<U11')

In [197]:
gdp_per_capita

array([52056.1234 , 40345.4565 , 45456.78564, 33245.56782, 34544.45888])

In [200]:
gdp_per_capita = np.array([52056.1234 , 40345.4565 , 45456.78564, 33245.56782, 34544.45888,34544.45845])

In [201]:
gdpdata = pd.Series(gdp_per_capita,index=countries)

In [202]:
gdpdata

luxembourg     52056.12340
Norway         40345.45650
Japan          45456.78564
Switzerland    33245.56782
USA            34544.45888
Qatar          34544.45845
dtype: float64

In [203]:
gdpdata2 = pd.Series(gdp_per_capita)

In [204]:
gdpdata2

0    52056.12340
1    40345.45650
2    45456.78564
3    33245.56782
4    34544.45888
5    34544.45845
dtype: float64

In [205]:
scalar_series = pd.Series(5,index=['a','b','c'])

In [206]:
scalar_series

a    5
b    5
c    5
dtype: int64

In [207]:
gdpdata[0]

52056.1234

In [208]:
gdpdata[-5]

40345.4565

In [209]:
gdpdata['USA']

34544.45888

In [210]:
gdpdata.loc['USA']

34544.45888

In [212]:
gdpdata.iloc[0]

52056.1234

In [213]:
ser = pd.Series([4, 7, -5, 3])

In [214]:
ser

0    4
1    7
2   -5
3    3
dtype: int64

In [215]:
ser.values

array([ 4,  7, -5,  3])

In [216]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [217]:
ser

0    4
1    7
2   -5
3    3
dtype: int64

In [218]:
ser2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [219]:
ser2

d    4
b    7
a   -5
c    3
dtype: int64

In [220]:
ser2['b']

7

In [221]:
ser2['b'] = 17

In [222]:
ser2

d     4
b    17
a    -5
c     3
dtype: int64

In [226]:
ser2[['c','d']]

c    3
d    4
dtype: int64

In [227]:
ser2[ser2 > 0]

d     4
b    17
c     3
dtype: int64

In [228]:
ser2

d     4
b    17
a    -5
c     3
dtype: int64

In [229]:
np.exp(ser2)

d    5.459815e+01
b    2.415495e+07
a    6.737947e-03
c    2.008554e+01
dtype: float64

In [230]:
'b' in ser2

True

In [231]:
sdata = {'paris': 35000, 'germany': 71000, 'greece': 16000, 'norway': 5000}

In [233]:
type(sdata)

dict

In [240]:
sdata.keys()

dict_keys(['paris', 'germany', 'greece', 'norway'])

In [241]:
sdata.values()

dict_values([35000, 71000, 16000, 5000])

In [242]:
ser3 = pd.Series(sdata)

In [243]:
ser3

paris      35000
germany    71000
greece     16000
norway      5000
dtype: int64

In [244]:
country = ['greece', 'paris', 'germany', 'norway']

In [245]:
ser4 = pd.Series(sdata, index=country)

In [246]:
ser4

greece     16000
paris      35000
germany    71000
norway      5000
dtype: int64

In [247]:
pd.isnull(ser4)

greece     False
paris      False
germany    False
norway     False
dtype: bool

In [248]:
result = ser3 + ser4

In [249]:
result

germany    142000
greece      32000
norway      10000
paris       70000
dtype: int64

In [252]:
ser4.name = 'population'

In [253]:
ser4

greece     16000
paris      35000
germany    71000
norway      5000
Name: population, dtype: int64

In [254]:
ser4.index.name = 'country'

In [255]:
ser4

country
greece     16000
paris      35000
germany    71000
norway      5000
Name: population, dtype: int64

In [256]:
data = {'eucountry': ['paris', 'germany', 'austria', 'sweden', 'Norway'],
'year': [2000, 2001, 2002, 2001, 2002],
'popul': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [257]:
type(data)

dict

In [258]:
frame = pd.DataFrame(data)

In [259]:
frame

eucountry  year  popul
0     paris  2000    1.5
1   germany  2001    1.7
2   austria  2002    3.6
3    sweden  2001    2.4
4    Norway  2002    2.9

In [262]:
frame2 = pd.DataFrame(data, columns=['eucountry', 'popul','year'])

In [263]:
frame2

eucountry  popul  year
0     paris    1.5  2000
1   germany    1.7  2001
2   austria    3.6  2002
3    sweden    2.4  2001
4    Norway    2.9  2002

In [264]:
frame3 = pd.DataFrame(data, columns=['year', 'eucountry', 'popul', 'debt'],
	 index=['one', 'two', 'three', 'four', 'five'])

In [265]:
frame3

year eucountry  popul debt
one    2000     paris    1.5  NaN
two    2001   germany    1.7  NaN
three  2002   austria    3.6  NaN
four   2001    sweden    2.4  NaN
five   2002    Norway    2.9  NaN

In [266]:
print(frame3['eucountry'])

one        paris
two      germany
three    austria
four      sweden
five      Norway
Name: eucountry, dtype: object


In [269]:
frame3.loc['three']

year            2002
eucountry    austria
popul            3.6
debt             NaN
Name: three, dtype: object

In [272]:
frame3.iloc[3]

year           2001
eucountry    sweden
popul           2.4
debt            NaN
Name: four, dtype: object

In [273]:
frame3

year eucountry  popul debt
one    2000     paris    1.5  NaN
two    2001   germany    1.7  NaN
three  2002   austria    3.6  NaN
four   2001    sweden    2.4  NaN
five   2002    Norway    2.9  NaN

In [274]:
frame3['debt'] = 16.5

In [275]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5  16.5
two    2001   germany    1.7  16.5
three  2002   austria    3.6  16.5
four   2001    sweden    2.4  16.5
five   2002    Norway    2.9  16.5

In [276]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5  16.5
two    2001   germany    1.7  16.5
three  2002   austria    3.6  16.5
four   2001    sweden    2.4  16.5
five   2002    Norway    2.9  16.5

In [277]:
frame3['debt'] = np.arange(5.)

In [278]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5   0.0
two    2001   germany    1.7   1.0
three  2002   austria    3.6   2.0
four   2001    sweden    2.4   3.0
five   2002    Norway    2.9   4.0

In [279]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [280]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [281]:
frame3['debt'] = val

In [282]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5   NaN
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [283]:
frame3['eastern'] = frame3.eucountry == 'paris'

In [284]:
frame3

year eucountry  popul  debt  eastern
one    2000     paris    1.5   NaN     True
two    2001   germany    1.7  -1.2    False
three  2002   austria    3.6   NaN    False
four   2001    sweden    2.4  -1.5    False
five   2002    Norway    2.9  -1.7    False

In [285]:
del frame3['eastern']

In [286]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5   NaN
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [289]:
frame3.drop(['one'])

year eucountry  popul  debt
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [290]:
frame3.drop(frame3.index[0])

year eucountry  popul  debt
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [291]:
frame3

year eucountry  popul  debt
one    2000     paris    1.5   NaN
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7