In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
distance = [10,15,17,24]

In [4]:
time = [.30,.47,.55,1.20]

In [6]:
np_distance = np.array(distance)

In [7]:
np_distance

array([10, 15, 17, 24])

In [8]:
np_time = np.array(time)

In [9]:
speed = np_distance/np_time

In [10]:
speed

array([33.33333333, 31.91489362, 30.90909091, 20.        ])

In [11]:
x = (1,2)

In [12]:
y = (3,4)

In [14]:
type(x)

tuple

In [15]:
type(y)

tuple

In [16]:
z = [x,y]

In [17]:
z

[(1, 2), (3, 4)]

In [18]:
type(z)

list

In [19]:
mda = np.array(z)

In [20]:
mda

array([[1, 2],
       [3, 4]])

In [21]:
mda[1,1]

4

In [22]:
mda.ndim

2

In [23]:
mda.size

4

In [24]:
mda.shape

(2, 2)

In [25]:
array_with_zeroes = np.zeros((3,3))

In [26]:
array_with_zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
array_with_zeroes.shape

(3, 3)

In [30]:
array_with_empty = np.empty((2,3))

In [31]:
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np_arange = np.arange(12)

In [33]:
np_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
np_arange.shape

(12,)

In [40]:
np_arange.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [41]:
np_linspace = np.linspace(1,6,5)

In [42]:
np_linspace

array([1.  , 2.25, 3.5 , 4.75, 6.  ])

In [43]:
x

(1, 2)

In [44]:
y

(3, 4)

In [45]:
z = (5,6)

In [46]:
z


(5, 6)

In [51]:
np.array([x,y,z])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
threeD_array = np.arange(27).reshape(3,3,3)

In [56]:
threeD_array.shape

(3, 3, 3)

In [61]:
n = threeD_array.ravel()


In [62]:
type(n)

numpy.ndarray

AttributeError: 'numpy.ndarray' object has no attribute 'hsplit'

In [64]:
f = np.array([x,y,z])

In [65]:
f

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
f[1:,0:]

array([[3, 4],
       [5, 6]])

In [67]:
f[1:,:0]


array([], shape=(2, 0), dtype=int32)

In [69]:
f[1:,:1]

array([[3],
       [5]])

In [70]:
first_trial_cyclist = [10,15,17,24]

In [71]:
second_trial_cyclist = [12,11,21,24]

In [72]:
type(first_trial_cyclist)

list

In [75]:
np_first_trial_cyclist = np.array(first_trial_cyclist)

In [76]:
np_second_trial_cylist = np.array(second_trial_cyclist)

In [77]:
result = np_first_trial_cyclist+np_second_trial_cylist

In [78]:
result

array([22, 26, 38, 48])

In [79]:
countries = np.array(['luxembourg','Norway','Japan','Switzerland','USA','Qatar'])

In [80]:
countries

array(['luxembourg', 'Norway', 'Japan', 'Switzerland', 'USA', 'Qatar'],
      dtype='<U11')

In [81]:
gdp_per_capita = np.array([52056.1234,40345.4565,45456.78564,33245.56782,34544.45888])

In [82]:
max_gdp_per_capita = gdp_per_capita.argmax()

In [83]:
max_gdp_per_capita

0

In [84]:
country_with_max_gdp_per_capita = countries[max_gdp_per_capita]

In [85]:
country_with_max_gdp_per_capita

'luxembourg'

In [86]:
for country in countries:
    print('ecalculating country {}'.format(country))

ecalculating country luxembourg
ecalculating country Norway
ecalculating country Japan
ecalculating country Switzerland
ecalculating country USA
ecalculating country Qatar


In [90]:
bdata = np.genfromtxt('Bank_full.csv', delimiter = ',', names= True)

In [91]:
bdata

array([(58., nan, nan, nan, nan, 2.143e+03, nan, nan, nan,  5., nan,  261., 1.,  -1.,  0., nan, nan),
       (44., nan, nan, nan, nan, 2.900e+01, nan, nan, nan,  5., nan,  151., 1.,  -1.,  0., nan, nan),
       (33., nan, nan, nan, nan, 2.000e+00, nan, nan, nan,  5., nan,   76., 1.,  -1.,  0., nan, nan),
       ...,
       (72., nan, nan, nan, nan, 5.715e+03, nan, nan, nan, 17., nan, 1127., 5., 184.,  3., nan, nan),
       (57., nan, nan, nan, nan, 6.680e+02, nan, nan, nan, 17., nan,  508., 4.,  -1.,  0., nan, nan),
       (37., nan, nan, nan, nan, 2.971e+03, nan, nan, nan, 17., nan,  361., 2., 188., 11., nan, nan)],
      dtype=[('age', '<f8'), ('job', '<f8'), ('marital', '<f8'), ('education', '<f8'), ('default', '<f8'), ('balance', '<f8'), ('housing', '<f8'), ('loan', '<f8'), ('contact', '<f8'), ('day', '<f8'), ('month', '<f8'), ('duration', '<f8'), ('campaign', '<f8'), ('pdays', '<f8'), ('previous', '<f8'), ('poutcome', '<f8'), ('y', '<f8')])

In [93]:
ser = pd.Series([4, 7, -5, 3])

In [94]:
ser

0    4
1    7
2   -5
3    3
dtype: int64

In [95]:
ser.values

array([ 4,  7, -5,  3], dtype=int64)

In [96]:
ser.index

RangeIndex(start=0, stop=4, step=1)

In [98]:
ser2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [99]:
ser2

d    4
b    7
a   -5
c    3
dtype: int64

In [102]:
ser2['d'] = 24

In [103]:
ser2['d']

24

In [104]:
ser2

d    24
b     7
a    -5
c     3
dtype: int64

In [105]:
ser2[['c', 'a', 'd']]

c     3
a    -5
d    24
dtype: int64

In [106]:
ser2[ser2 > 0]

d    24
b     7
c     3
dtype: int64

In [109]:
'b' in ser2

True

In [110]:
sdata = {'paris': 35000, 'germany': 71000, 'greece': 16000, 'norway': 5000}

In [111]:
type(sdata)

dict

In [112]:
myser = pd.Series(sdata)

In [113]:
myser

paris      35000
germany    71000
greece     16000
norway      5000
dtype: int64

In [114]:
myser.index

Index(['paris', 'germany', 'greece', 'norway'], dtype='object')

In [115]:
myser.values

array([35000, 71000, 16000,  5000], dtype=int64)

In [116]:
myser['paris']

35000

In [117]:
country = ['greece', 'paris', 'germany', 'norway']

In [118]:
type(country)

list

In [119]:
ser4 = pd.Series(sdata, index=country)

In [120]:
ser4

greece     16000
paris      35000
germany    71000
norway      5000
dtype: int64

In [121]:
pd.isnull(ser4)

greece     False
paris      False
germany    False
norway     False
dtype: bool

In [123]:
ser3 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [124]:
ser4 = pd.Series([41, 71, -15, 3], index=['e', 'b', 'a', 'd'])

In [125]:
ser3

d    4
b    7
a   -5
c    3
dtype: int64

In [126]:
ser4

e    41
b    71
a   -15
d     3
dtype: int64

In [127]:
ser4 + ser3

a   -20.0
b    78.0
c     NaN
d     7.0
e     NaN
dtype: float64

In [128]:
ser4

e    41
b    71
a   -15
d     3
dtype: int64

In [129]:
ser4.name = 'calc'

In [130]:
ser4

e    41
b    71
a   -15
d     3
Name: calc, dtype: int64

In [132]:
ser4.index.name = 'letters'

In [133]:
ser4

letters
e    41
b    71
a   -15
d     3
Name: calc, dtype: int64

In [134]:
ser.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [135]:
ser

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [136]:
ser

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [137]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})

In [138]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [139]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],'data2': range(3)})

In [140]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [141]:
pd.merge(df1, df2)

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [142]:
data = {'eucountry': ['paris', 'germany', 'austria', 'sweden', 'Norway'],
'year': [2000, 2001, 2002, 2001, 2002],
'popul': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [143]:
type(data)

dict

In [144]:
frame = pd.DataFrame(data)

In [145]:
frame

eucountry  year  popul
0     paris  2000    1.5
1   germany  2001    1.7
2   austria  2002    3.6
3    sweden  2001    2.4
4    Norway  2002    2.9

In [146]:
pd.DataFrame(data, columns=['year', 'eucountry', 'popul'])

year eucountry  popul
0  2000     paris    1.5
1  2001   germany    1.7
2  2002   austria    3.6
3  2001    sweden    2.4
4  2002    Norway    2.9

In [147]:
frame2 = pd.DataFrame(data, columns=['year', 'eucountry', 'popul', 'debt'],
	 index=['one', 'two', 'three', 'four', 'five'])

In [148]:
frame2

year eucountry  popul debt
one    2000     paris    1.5  NaN
two    2001   germany    1.7  NaN
three  2002   austria    3.6  NaN
four   2001    sweden    2.4  NaN
five   2002    Norway    2.9  NaN

In [149]:
frame2['eucountry']

one        paris
two      germany
three    austria
four      sweden
five      Norway
Name: eucountry, dtype: object

In [154]:
frame2.loc['three']

year            2002
eucountry    austria
popul            3.6
debt             NaN
Name: three, dtype: object

In [155]:
frame2


year eucountry  popul debt
one    2000     paris    1.5  NaN
two    2001   germany    1.7  NaN
three  2002   austria    3.6  NaN
four   2001    sweden    2.4  NaN
five   2002    Norway    2.9  NaN

In [156]:
frame2['debt'] = 20

In [157]:
frame2

year eucountry  popul  debt
one    2000     paris    1.5    20
two    2001   germany    1.7    20
three  2002   austria    3.6    20
four   2001    sweden    2.4    20
five   2002    Norway    2.9    20

In [158]:
frame2['debt'] = np.arange(5.)

In [159]:
frame2

year eucountry  popul  debt
one    2000     paris    1.5   0.0
two    2001   germany    1.7   1.0
three  2002   austria    3.6   2.0
four   2001    sweden    2.4   3.0
five   2002    Norway    2.9   4.0

In [160]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [161]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [162]:
frame2['debt'] = val

In [163]:
frame2

year eucountry  popul  debt
one    2000     paris    1.5   NaN
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [164]:
frame2['eastern'] = frame2.eucountry == 'paris'

In [165]:
frame2

year eucountry  popul  debt  eastern
one    2000     paris    1.5   NaN     True
two    2001   germany    1.7  -1.2    False
three  2002   austria    3.6   NaN    False
four   2001    sweden    2.4  -1.5    False
five   2002    Norway    2.9  -1.7    False

In [167]:
del frame2['eastern']

In [168]:
frame2

year eucountry  popul  debt
one    2000     paris    1.5   NaN
two    2001   germany    1.7  -1.2
three  2002   austria    3.6   NaN
four   2001    sweden    2.4  -1.5
five   2002    Norway    2.9  -1.7

In [169]:
pop = {'norway': {2001: 2.4, 2002: 2.9},
	'denmark': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [170]:
pop

{'norway': {2001: 2.4, 2002: 2.9},
 'denmark': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [171]:
frame3 = pd.DataFrame(pop)

In [172]:
frame3


norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2000     NaN      1.5

In [173]:
print(frame3.T)

         2001  2002  2000
norway    2.4   2.9   NaN
denmark   1.7   3.6   1.5


In [174]:
frame3

norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2000     NaN      1.5

In [175]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2003     NaN      NaN

In [177]:
frame3['norway'][:-1]

2001    2.4
2002    2.9
Name: norway, dtype: float64

In [178]:
frame3

norway  denmark
2001     2.4      1.7
2002     2.9      3.6
2000     NaN      1.5

In [179]:
frame3.index.name = 'year'; frame3.columns.name = 'eucountry'

In [180]:
frame3

eucountry  norway  denmark
year                      
2001          2.4      1.7
2002          2.9      3.6
2000          NaN      1.5

In [181]:
item = pd.Series(range(3),index = ['a','b','c'])
index = item.index

In [182]:
index

Index(['a', 'b', 'c'], dtype='object')

In [183]:
index[1:]

Index(['b', 'c'], dtype='object')

In [184]:
ser = pd.Series([1,2,3,4], index=['d','b','c','a'])

In [185]:
ser

d    1
b    2
c    3
a    4
dtype: int64

In [186]:
ser1 = ser.reindex(['a','b','c','d'])

In [187]:
ser1

a    4
b    2
c    3
d    1
dtype: int64

In [188]:
ser3 = ser1.reindex(['a','b','c','d','e'])

In [189]:
ser3

a    4.0
b    2.0
c    3.0
d    1.0
e    NaN
dtype: float64

In [190]:
ser3 = ser1.reindex(['a','b','c','d','e'],fill_value=0)

In [191]:
ser3

a    4
b    2
c    3
d    1
e    0
dtype: int64

In [192]:
ser4 = pd.Series(['cricket','football','basketball'],index=[0,2,4])

In [193]:
ser4

0       cricket
2      football
4    basketball
dtype: object

In [194]:
ser4.reindex(range(6),method='ffill')

0       cricket
1       cricket
2      football
3      football
4    basketball
5    basketball
dtype: object

In [196]:
ser5 = pd.Series(['cricket','football','basketball'],index=[0,2,4])
ser5.reindex(range(6),method='bfill')

0       cricket
1      football
2      football
3    basketball
4    basketball
5           NaN
dtype: object